=== Urwumpe/mars-sim/mars-sim-core/src/main/resources/xml/country/country.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="last-name">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="first-name">
        <xs:complexType>
            <xs:attribute name="value" type="xs:string"/>
            <xs:attribute name="gender" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="country">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="first-name-list">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="first-name" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="last-name-list">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="last-name" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Urwumpe/mars-sim/mars-sim-core/src/main/resources/xml/country/country_uk.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
    name="UK">
    <first-name-list>
        <first-name value="Oliver" gender="male" />
        <first-name value="Jacob" gender="male" />
        <first-name value="Charlie" gender="male" />
        <first-name value="Jack" gender="male" />
        <first-name value="Noah" gender="male" />
        <first-name value="Alfie" gender="male" />
        <first-name value="Oscar" gender="male" />
        <first-name value="William" gender="male" />
        <first-name value="George" gender="male" />
        <first-name value="Harry" gender="male" />

        <first-name value="Amelia" gender="female" />
        <first-name value="Olivia" gender="female" />
        <first-name value="Emily" gender="female" />
        <first-name value="Isla" gender="female" />
        <first-name value="Ava" gender="female" />
        <first-name value="Jessica" gender="female" />
        <first-name value="Ella" gender="female" />
        <first-name value="Isabella" gender="female" />
        <first-name value="Poppy" gender="female" />
        <first-name value="Mia" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 common UK surnames, taking into account individual countries -->

        <last-name value="Brown" />
        <last-name value="Campbell" />
        <last-name value="Davies" />
        <last-name value="Evans" />
        <last-name value="Jones" />
        <last-name value="Robertson" />
        <last-name value="Smith" />
        <last-name value="Taylor" />
        <last-name value="Thomson" />
        <last-name value="Wilson" />
    </last-name-list>
</country>

=== Urwumpe/mars-sim/mars-sim-core/src/main/resources/xml/country/country_austria.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
        name="Austria">
    <economics-data>
		 <GDP value="471,400"/>
		 <PPP value="614,312"/>
		 <population value="8.939617"/>
		 <GDP-growth value="5"/>
	</economics-data>
	
	<!-- Taken from 
  	  	https://en.wikipedia.org/wiki/List_of_countries_by_median_age
    	https://www.worlddata.info/average-bodyheight.php -->
    <characteristics median-age-male="43.1" median-age-female="45.8" 	
				average-male-height="178" average-female-height="166"
	            average-male-weight="89.6" average-female-weight="68.1"/>
	            	
    <first-name-list>
        <first-name value="Lukas" gender="male" />
        <first-name value="Maximilian" gender="male" />
        <first-name value="Jakob" gender="male" />
        <first-name value="David" gender="male" />
        <first-name value="Tobias" gender="male" />
        <first-name value="Paul" gender="male" />
        <first-name value="Jonas" gender="male" />
        <first-name value="Felix" gender="male" />
        <first-name value="Alexander" gender="male" />
        <first-name value="Elias" gender="male" />

        <first-name value="Anna" gender="female" />
        <first-name value="Hannah" gender="female" />
        <first-name value="Sophia" gender="female" />
        <first-name value="Emma" gender="female" />
        <first-name value="Marie" gender="female" />
        <first-name value="Lena" gender="female" />
        <first-name value="Sarah" gender="female" />
        <first-name value="Sophie" gender="female" />
        <first-name value="Laura" gender="female" />
        <first-name value="Mia" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Austrian surnames -->
        <last-name value="Bauer" />
        <last-name value="Gruber" />
        <last-name value="Hofer" />
        <last-name value="Huber" />
        <last-name value="Mayer" />
        <last-name value="Moser" />
        <last-name value="Muller" />
        <last-name value="Pichler" />
        <last-name value="Steiner" />
        <last-name value="Wagner" />
    </last-name-list>
</country>

=== Urwumpe/mars-sim/mars-sim-core/src/main/resources/xml/country/country_luxembourg.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
        name="Luxembourg">
     <economics-data>
		 <GDP value="82,274.812251"/>
		 <PPP value="86,117"/>
		 <population value="0.647599"/>
		 <GDP-growth value="1.55"/>
	</economics-data>
	
	<!-- Taken from 
  	  	https://en.wikipedia.org/wiki/List_of_countries_by_median_age
    	https://www.worlddata.info/average-bodyheight.php -->
    <characteristics median-age-male="38.9" median-age-female="40.0" 	
				average-male-height="178" average-female-height="165"
	            average-male-weight="85.2" average-female-weight="69.1"/>
		
    <first-name-list>
        <first-name value="Gabriel" gender="male" />
        <first-name value="Leo" gender="male" />
        <first-name value="Luca" gender="male" />
        <first-name value="Noah" gender="male" />
        <first-name value="David" gender="male" />
        <first-name value="Tom" gender="male" />
        <first-name value="Ben" gender="male" />
        <first-name value="Fränk" gender="male" />
        <first-name value="Andy" gender="male" />
        <first-name value="Teo" gender="male" />

        <first-name value="Emma" gender="female" />
        <first-name value="Lara" gender="female" />
        <first-name value="Zoé" gender="female" />
        <first-name value="Amy" gender="female" />
        <first-name value="Sarah" gender="female" />
        <first-name value="Charlotte" gender="female" />
        <first-name value="Emily" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Luxembourgish surnames -->

        <last-name value="Hoffmann" />
        <last-name value="Klein" />
        <last-name value="Muller" />
        <last-name value="Reuter" />
        <last-name value="Schmit" />
        <last-name value="Schmitz" />
        <last-name value="Schroeder" />
        <last-name value="Thill" />
        <last-name value="Wagner" />
        <last-name value="Weber" />
    </last-name-list>
</country>

=== Urwumpe/mars-sim/mars-sim-core/src/main/resources/xml/country/country_ireland.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
    name="Ireland">
     <economics-data>
		 <GDP value="529,245"/>
		 <PPP value="645,565"/>
		 <population value="5.023109"/>
		 <GDP-growth value="11.97"/>
	</economics-data>
	
	<!-- Taken from 
  	  	https://en.wikipedia.org/wiki/List_of_countries_by_median_age
    	https://www.worlddata.info/average-bodyheight.php -->
    <characteristics median-age-male="37.4" median-age-female="38.2" 	
				average-male-height="179" average-female-height="164"
	            average-male-weight="89.2" average-female-weight="73.1"/>
	            
    <first-name-list>
        <first-name value="Jack" gender="male" />
        <first-name value="James" gender="male" />
        <first-name value="Daniel" gender="male" />
        <first-name value="Conor" gender="male" />
        <first-name value="SeÃ¡n" gender="male" />
        <first-name value="Adam" gender="male" />
        <first-name value="Noah" gender="male" />
        <first-name value="Michael" gender="male" />
        <first-name value="Charlie" gender="male" />
        <first-name value="Luke" gender="male" />

        <first-name value="Emily" gender="female" />
        <first-name value="Emma" gender="female" />
        <first-name value="Ava" gender="female" />
        <first-name value="Sophie" gender="female" />
        <first-name value="Amelia" gender="female" />
        <first-name value="Ella" gender="female" />
        <first-name value="Lucy" gender="female" />
        <first-name value="Grace" gender="female" />
        <first-name value="Chloe" gender="female" />
        <first-name value="Mia" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Irish surnames -->

        <last-name value="Byrne" />
        <last-name value="Kelly" />
        <last-name value="Murphy" />
        <last-name value="Ryan" />
        <last-name value="Smith" />
        <last-name value="Sullivan" />
        <last-name value="O'Brien" />
        <last-name value="O'Connor" />
        <last-name value="O'Neill" />
        <last-name value="Walsh" />
    </last-name-list>
</country>

=== Urwumpe/mars-sim/mars-sim-core/src/main/resources/xml/country/country_the_netherlands.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
    name="The Netherlands">
    <first-name-list>
        <first-name value="Liam" gender="male" />
        <first-name value="Sem" gender="male" />
        <first-name value="Lucas" gender="male" />
        <first-name value="Luuk" gender="male" />
        <first-name value="Noah" gender="male" />
        <first-name value="Milan" gender="male" />
        <first-name value="Daan" gender="male" />
        <first-name value="Levi" gender="male" />
        <first-name value="Finn" gender="male" />
        <first-name value="Jesse" gender="male" />
        <first-name value="Emma" gender="female" />
        <first-name value="Julia" gender="female" />
        <first-name value="Sophie" gender="female" />
        <first-name value="Anna" gender="female" />
        <first-name value="Mila" gender="female" />
        <first-name value="Eva" gender="female" />
        <first-name value="Tess" gender="female" />
        <first-name value="Lotte" gender="female" />
        <first-name value="Sara" gender="female" />
        <first-name value="ZoÃ«" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Dutch surnames -->

        <last-name value="Bakker" />
        <last-name value="De Boer" />
        <last-name value="De Jong" />
        <last-name value="De Vries" />
        <last-name value="Janssen" />
        <last-name value="Meijer" />
        <last-name value="Smit" />
        <last-name value="Van den Berg" />
        <last-name value="Van Dijk" />
        <last-name value="Visser" />
    </last-name-list>
</country>

=== Urwumpe/mars-sim/mars-sim-core/src/main/resources/xml/country/country_denmark.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="country.xsd"
     name="Denmark">
    <first-name-list>
        <first-name value="William" gender="male" />
        <first-name value="Lucas" gender="male" />
        <first-name value="Malthe" gender="male" />
        <first-name value="Noah" gender="male" />
        <first-name value="Emil" gender="male" />
        <first-name value="Victor" gender="male" />
        <first-name value="Oscar" gender="male" />
        <first-name value="Alfred" gender="male" />
        <first-name value="Oliver" gender="male" />
        <first-name value="Frederik" gender="male" />
        <first-name value="Carl" gender="male" />
        <first-name value="Elias" gender="male" />

        <first-name value="Sofie" gender="female" />
        <first-name value="Alma" gender="female" />
        <first-name value="Freja" gender="female" />
        <first-name value="Anna" gender="female" />
        <first-name value="Ella" gender="female" />
        <first-name value="Emma" gender="female" />
        <first-name value="Laura" gender="female" />
        <first-name value="Clara" gender="female" />
        <first-name value="Maja" gender="female" />
        <first-name value="Alberte" gender="female" />
        <first-name value="Ida" gender="female" />
        <first-name value="Agnes" gender="female" />

        <first-name value="Eva" gender="female" />
        <first-name value="Hanne" gender="female" />
        <first-name value="Marie" gender="female" />
        <first-name value="Rosa" gender="female" />
        <first-name value="Else" gender="female" />
        <first-name value="Lea" gender="female" />
        <first-name value="Ronja" gender="female" />
        <first-name value="Isabella" gender="female" />
        <first-name value="Lilja" gender="female" />
        <first-name value="Liva" gender="female" />
        <first-name value="Mia" gender="female" />
        <first-name value="Gitte" gender="female" />
    </first-name-list>
    <last-name-list>
        <!-- 10 most common Danish surnames plus a little more -->

        <last-name value="Andersen" />
        <last-name value="Christensen" />
        <last-name value="Hansen" />
        <last-name value="Jensen" />
        <last-name value="Jørgensen" />
        <last-name value="Larsen" />
        <last-name value="Nielsen" />
        <last-name value="Pedersen" />
        <last-name value="Rasmussen" />
        <last-name value="Sørensen" />
        <last-name value="Rovsing" />
        <last-name value="Krogh" />
        <last-name value="Lund" />
    </last-name-list>
</country>
