<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE construction [
	<!ELEMENT construction (foundation-list, frame-list, building-list)>
	<!ELEMENT foundation-list (foundation*)>
	<!ELEMENT foundation (resource*, part*, vehicle*)>
	<!ATTLIST foundation name CDATA #REQUIRED>
	<!ATTLIST foundation width CDATA #REQUIRED>
	<!ATTLIST foundation length CDATA #REQUIRED>
	<!ATTLIST foundation base-level CDATA #REQUIRED>
	<!ATTLIST foundation constructable (true|false) #REQUIRED>
	<!ATTLIST foundation salvagable (true|false) #REQUIRED>
	<!ATTLIST foundation work-time CDATA #REQUIRED>
	<!ATTLIST foundation skill-required CDATA #REQUIRED>
	<!ELEMENT resource EMPTY>
	<!ATTLIST resource name CDATA #REQUIRED>
	<!ATTLIST resource amount CDATA #REQUIRED>
	<!ELEMENT part EMPTY>
	<!ATTLIST part name CDATA #REQUIRED>
	<!ATTLIST part number CDATA #REQUIRED>
	<!ELEMENT vehicle (attachment-part*)>
	<!ATTLIST vehicle type CDATA #REQUIRED>
	<!ELEMENT attachment-part EMPTY>
	<!ATTLIST attachment-part name CDATA #REQUIRED>
	<!ELEMENT frame-list (frame*)>
	<!ELEMENT frame (resource*, part*, vehicle*)>
	<!ATTLIST frame name CDATA #REQUIRED>
	<!ATTLIST frame width CDATA #REQUIRED>
	<!ATTLIST frame length CDATA #REQUIRED>
	<!ATTLIST frame base-level CDATA #REQUIRED>
	<!ATTLIST frame constructable (true|false) #REQUIRED>
	<!ATTLIST frame salvagable (true|false) #REQUIRED>
	<!ATTLIST frame work-time CDATA #REQUIRED>
	<!ATTLIST frame skill-required CDATA #REQUIRED>
	<!ATTLIST frame foundation CDATA #REQUIRED>
	<!ELEMENT building-list (building*)>
	<!ELEMENT building (resource*, part*, vehicle*)>
	<!ATTLIST building name CDATA #REQUIRED>
	<!ATTLIST building width CDATA #REQUIRED>
	<!ATTLIST building length CDATA #REQUIRED>
	<!ATTLIST building base-level CDATA #REQUIRED>
	<!ATTLIST building constructable (true|false) #REQUIRED>
	<!ATTLIST building salvagable (true|false) #REQUIRED>
	<!ATTLIST building work-time CDATA #REQUIRED>
	<!ATTLIST building skill-required CDATA #REQUIRED>
	<!ATTLIST building frame CDATA #REQUIRED>
]>

<construction>
	<foundation-list>

		<foundation name="surface foundation 3m x 2m" width="2.0" length="3.0" base-level="0" 
		 constructable="true" salvagable="true" work-time="0.4" skill-required="1" >
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="soil compactor" />
			</vehicle>
		</foundation>

		<foundation name="surface foundation 5m x 5m" width="5.0" length="5.0" base-level="0" 
		 constructable="true" salvagable="true" work-time="0.8" skill-required="1" >
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="soil compactor" />
			</vehicle>
		</foundation>
	
		<foundation name="surface foundation 10m x 5m" width="5.0" length="10.0" base-level="0" 
		 constructable="true" salvagable="true" work-time="1.2" skill-required="1" >
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="soil compactor" />
			</vehicle>
		</foundation>
		
		<!-- surface foundation 7m x 9m is setting for medium modular frame. work-time = 3.0 -->
		<foundation name="surface foundation 7m x 9m" width="9.0" length="7.0" base-level="0" 
		 constructable="true" salvagable="true" work-time="1.2" skill-required="1" >
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="soil compactor" />
			</vehicle>
		</foundation>
		
		<foundation name="surface foundation 9m x 9m" width="9.0" length="9.0" base-level="-1" 
		 constructable="true" salvagable="true" work-time="1.4" skill-required="1" >
			<vehicle type="light utility vehicle" >    
				<attachment-part name="bulldozer blade" />
				<attachment-part name="backhoe" />
			</vehicle>
		</foundation>

		<foundation name="surface foundation 8m x 11m" width="8.0" length="11.0" base-level="-1" 
		 constructable="true" salvagable="true" work-time="1.8" skill-required="1" >
			<vehicle type="light utility vehicle" >    
				<attachment-part name="bulldozer blade" />
				<attachment-part name="backhoe" />
			</vehicle>
		</foundation>
						
		<foundation name="surface foundation 12m x 18m" width="18.0" length="12.0" base-level="0" 
		 constructable="true" salvagable="true" work-time="2.4" skill-required="1" >
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="soil compactor" />
			</vehicle>
		</foundation>
						
		<foundation name="subsurface foundation 5m x 5m x 3m" width="5.0" length="5.0" base-level="-1" 
		 constructable="true" salvagable="true" work-time="8.0" skill-required="1" >
			<resource name="concrete" amount="500.0" />
			<resource name="water" amount="200.0" />
			<vehicle type="light utility vehicle" >    
				<attachment-part name="bulldozer blade" />
				<attachment-part name="backhoe" />
			</vehicle>
		</foundation>	
		
		<foundation name="subsurface foundation 10m x 10m x 3m" width="10.0" length="10.0" base-level="-1" 
		 constructable="true" salvagable="true" work-time="15.0" skill-required="1" >
			<resource name="concrete" amount="2500.0" />
			<resource name="water" amount="800.0" />
			<vehicle type="light utility vehicle" >    
				<attachment-part name="bulldozer blade" />
				<attachment-part name="backhoe" />
			</vehicle>
		</foundation>
				
		<foundation name="ramped subsurface foundation 15m x 18m x 5m" width="18.0" length="15.0" base-level="-1" 
		 constructable="true" salvagable="true" work-time="20.0" skill-required="1" >
			<resource name="concrete" amount="2500.0" />
			<resource name="water" amount="800.0" />
			<vehicle type="light utility vehicle" >    
				<attachment-part name="bulldozer blade" />
				<attachment-part name="backhoe" />
			</vehicle>
		</foundation>
		
		<foundation name="subsurface foundation 5m x 10m x 3m" width="5.0" length="10.0" base-level="-1" 
		 constructable="true" salvagable="true" work-time="12.0" skill-required="1" >
			<resource name="concrete" amount="1200.0" />
			<resource name="water" amount="400.0" />
			<vehicle type="light utility vehicle" >    
				<attachment-part name="bulldozer blade" />
				<attachment-part name="backhoe" />
			</vehicle>
		</foundation>
		
		
		<foundation name="shallow borehole drilling site" width="5.0" length="10.0" base-level="0" 
		 constructable="true" salvagable="true" work-time="10.0" skill-required="3" >
		 	<resource name="water" amount="100.0" />
		 	<part name="bore drill bit" number="1" />
		 	<part name="bore drill pipe" number="20" />
			<vehicle type="light utility vehicle" >    
				<attachment-part name="crane boom" />
				<attachment-part name="drilling rig" />
			</vehicle>
		</foundation>
		 
		<foundation name="deep borehole drilling site" width="10.0" length="15.0" base-level="0" 
		 constructable="true" salvagable="true" work-time="15.0" skill-required="4" >
		 	<resource name="water" amount="200.0" />
		 	<part name="bore drill bit" number="4" />
		 	<part name="bore drill pipe" number="60" />
			<vehicle type="light utility vehicle" >    
				<attachment-part name="crane boom" />
				<attachment-part name="drilling rig" />
			</vehicle>
		</foundation>
		
		<!-- Surface foundation with a variable width and length is dynamically set. -->
		<!-- (Used for hallway construction) -->
		<foundation name="surface foundation variable size" width="-1.0" length="-1.0" base-level="0" 
		 constructable="true" salvagable="true" work-time="1.0" skill-required="1" >
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="soil compactor" />
			</vehicle>
		</foundation>

		<!-- Subsurface foundation with a variable width and length that is dynamically set. -->
		<!-- (Used for tunnel construction)	-->
		<foundation name="subsurface foundation variable size" width="-1.0" length="-1.0" base-level="-1" 
		 constructable="true" salvagable="true" work-time="2.0" skill-required="1" >
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="backhoe" />
			</vehicle>
		</foundation>

	</foundation-list>


	<frame-list>
	
		<frame name="steel frame tower" width="5.0" length="5.0" base-level="0" constructable="true" 
		 salvagable="true" work-time="20.0" skill-required="2" foundation="surface foundation 5m x 5m" >
			<resource name="concrete" amount="50.0" />
			<resource name="water" amount="20.0" />
			<part name="steel truss" number="20" />
			<part name="steel cable" number="6" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>
		
		<frame name="small steel frame" width="5.0" length="5.0" base-level="0" constructable="true" 
		 salvagable="true" work-time="10.0" skill-required="1" foundation="surface foundation 5m x 5m" >
			<resource name="concrete" amount="25.0" />
			<resource name="water" amount="10.0" />
			<part name="steel truss" number="10" />
			<part name="steel sheet" number="5" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>
	
		<frame name="array frame" width="5.0" length="10.0" base-level="0" constructable="true" 
		 salvagable="true" work-time="20.0" skill-required="2" foundation="surface foundation 10m x 5m" >
			<resource name="concrete" amount="50.0" />
			<resource name="water" amount="20.0" />
			<part name="steel truss" number="20" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>
		
		<frame name="brick bin frame" width="2.0" length="3.0" base-level="0" constructable="true" 
		 salvagable="true" work-time="5.0" skill-required="1" foundation="surface foundation 3m x 2m" >
			<resource name="mortar" amount="90.0" />
			<resource name="water" amount="90.0" />
			<part name="brick" number="200" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>
		
		<frame name="small brick shed frame" width="5.0" length="5.0" base-level="-1" constructable="true" 
		 salvagable="true" work-time="40.0" skill-required="1" foundation="subsurface foundation 5m x 5m x 3m" >
			<resource name="mortar" amount="250.0" />
			<resource name="water" amount="250.0" />
			<part name="brick" number="250" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>
		
		<!-- Note: the round hab frame is just for salvaging and cannot be constructed insitu. -->
		<frame name="round hab frame" width="9.0" length="9.0" base-level="0" constructable="false" 
		 salvagable="true" work-time="10.0" skill-required="2" foundation="surface foundation 9m x 9m" >
			<part name="steel ingot" number="90" />
			<part name="aluminum ingot" number="90" />
			<part name="plastic pipe" number="50" />
			<part name="valve" number="10" />
			<part name="electrical wire" number="200" />
			<part name="wire connector" number="200" />
			<part name="power cable" number="20" />
			<part name="steel pipe" number="40" />
			<part name="gasket" number="40" />
			<part name="solar panel" number="4" />
		</frame>
		
		<!-- Note: the inflatable frame is just for salvaging and cannot be constructed insitu. -->
		<frame name="inflatable frame" width="6.0" length="9.0" base-level="0" constructable="false" 
		 salvagable="true" work-time="10.0" skill-required="2" foundation="surface foundation 7m x 9m" >
			<part name="aluminum ingot" number="60" />
			<part name="plastic sheet" number="50" />
			<part name="plastic pipe" number="50" />
			<part name="valve" number="30" />
			<part name="gasket" number="30" />
			<part name="electrical wire" number="40" />
			<part name="wire connector" number="40" />
			<part name="power cable" number="12" />
		</frame>
		
		
		<!-- Note: the atmospheric processor frame is just for salvaging and cannot be constructed insitu. -->
		<frame name="atmospheric processor frame" width="8.0" length="11.0" base-level="0" constructable="false" 
		 salvagable="true" work-time="12.0" skill-required="3" foundation="surface foundation 8m x 11m" >
			<part name="steel ingot" number="90" />
			<part name="aluminum ingot" number="90" />
			<part name="plastic pipe" number="50" />
			<part name="valve" number="20" />
			<part name="electrical wire" number="50" />
			<part name="wire connector" number="50" />
			<part name="power cable" number="10" />
			<part name="steel pipe" number="10" />
			<part name="gasket" number="18" />
		</frame>
		
		<!-- Note: the medium modular frame is just for salvaging and cannot be constructed insitu. -->
		<frame name="medium modular frame" width="7.0" length="9.0" base-level="0" constructable="false" 
		 salvagable="true" work-time="10.0" skill-required="2" foundation="surface foundation 7m x 9m" >
			<part name="steel ingot" number="60" />
			<part name="aluminum ingot" number="60" />
			<part name="plastic pipe" number="40" />
			<part name="valve" number="50" />
			<part name="electrical wire" number="50" />
			<part name="wire connector" number="50" />
			<part name="power cable" number="15" />
			<part name="gasket" number="15" />
		</frame>
		
		<!-- Note: the large greenhouse frame is just for salvaging and cannot be constructed insitu. -->
		<frame name="large greenhouse frame" width="12.0" length="18.0" base-level="0" constructable="false" 
		 salvagable="true" work-time="16.0" skill-required="3" foundation="surface foundation 12m x 18m" >
			<part name="steel ingot" number="200" />
			<part name="aluminum ingot" number="200" />
			<part name="glass sheet" number="50" />
			<part name="plastic pipe" number="150" />
			<part name="valve" number="90" />
			<part name="gasket" number="90" />
			<part name="electrical wire" number="120" />
			<part name="wire connector" number="120" />
			<part name="power cable" number="30" />
		</frame>
		
		<!-- Note: the garage frame is just for salvaging and cannot be constructed insitu. -->
		<frame name="garage frame" width="12.0" length="16.0" base-level="0" constructable="false" 
		 salvagable="true" work-time="14.0" skill-required="2" foundation="surface foundation 12m x 18m" >
			<part name="steel ingot" number="190" />
			<part name="aluminum ingot" number="190" />
			<part name="plastic pipe" number="100" />
			<part name="valve" number="50" />
			<part name="electrical wire" number="50" />
			<part name="wire connector" number="50" />
			<part name="power cable" number="20" />
			<part name="gasket" number="40" />
		</frame>
		
		<frame name="small areothermal well frame" width="5.0" length="10.0" base-level="0" constructable="true" 
		 salvagable="true" work-time="7.0" skill-required="2" foundation="shallow borehole drilling site" >
			<resource name="concrete" amount="700.0" />
			<resource name="water" amount="700.0" />
			<part name="steel truss" number="10" />
			<part name="steel sheet" number="15" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>
		
		<frame name="large areothermal well frame" width="10.0" length="15.0" base-level="0" constructable="true" 
		 salvagable="true" work-time="12.0" skill-required="3" foundation="deep borehole drilling site" >
			<resource name="concrete" amount="2000.0" />
			<resource name="water" amount="2000.0" />
			<part name="steel truss" number="20" />
			<part name="steel sheet" number="30" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>
		
		<frame name="round vaulted brick frame" width="10.0" length="10.0" base-level="-1" constructable="true" 
		 salvagable="true" work-time="10.0" skill-required="2" foundation="subsurface foundation 10m x 10m x 3m" >
			<resource name="mortar" amount="1200.0" />
			<resource name="water" amount="1200.0" />
			<part name="brick" number="1200" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>
		
		<frame name="large garage brick frame" width="15.0" length="18.0" base-level="-1" constructable="true" 
		 salvagable="true" work-time="15.0" skill-required="3" foundation="ramped subsurface foundation 15m x 18m x 5m" >
			<resource name="mortar" amount="3500.0" />
			<resource name="water" amount="3500.0" />
			<part name="brick" number="3500" />
			<part name="steel truss" number="30" />
			<part name="steel sheet" number="50" />
			<part name="aluminum sheet" number="50" />
			<part name="plastic pipe" number="100" />
			<part name="valve" number="50" />
			<part name="electrical wire" number="50" />
			<part name="wire connector" number="50" />
			<part name="power cable" number="20" />
			<part name="gasket" number="40" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>
		
		<frame name="vaulted glass brick frame" width="5.0" length="10.0" base-level="-1" constructable="true" 
		 salvagable="true" work-time="7.0" skill-required="3" foundation="subsurface foundation 5m x 10m x 3m" >
			<resource name="mortar" amount="700.0" />
			<resource name="water" amount="700.0" />
			<part name="brick" number="700" />
			<part name="steel truss" number="4" />
			<part name="aluminum sheet" number="7" />
			<part name="glass sheet" number="10" />
			<part name="plastic pipe" number="7" />
			<part name="valve" number="5" />
			<part name="gasket" number="5" />
			<part name="electrical wire" number="6" />
			<part name="wire connector" number="6" />
			<part name="power cable" number="3" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>
		
		<!-- Note hallway frame length is variable. -->
		<frame name="hallway frame" width="2.0" length="-1.0" base-level="0" constructable="true" 
		 salvagable="true" work-time="3.0" skill-required="1" foundation="surface foundation variable size" >
			<resource name="concrete" amount="60.0" />
			<resource name="water" amount="60.0" />
			<part name="steel post" number="5" />
		</frame>
		
		<!-- Note brick tunnel frame length is variable. -->
		<frame name="brick tunnel frame" width="3.0" length="-1.0" base-level="-1" constructable="true" 
		 salvagable="true" work-time="6.0" skill-required="1" foundation="subsurface foundation variable size" >
			<resource name="mortar" amount="90.0" />
			<resource name="water" amount="90.0" />
			<part name="brick" number="90" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>
		
	</frame-list>

	<building-list>

		<building name="wind turbine" width="5.0" length="5.0" base-level="0" constructable="true" 
		 salvagable="true" work-time="10.0" skill-required="3" frame="steel frame tower" >
			<part name="wind turbine blade" number="4" />
			<part name="turbine generator" number="1" />
			<part name="power cable" number="6" />
			<part name="electrical wire" number="20" />
			<part name="wire connector" number="20" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</building>
	
		<building name="solar photovoltaic array" width="5.0" length="10.0" base-level="0" constructable="true" 
		 salvagable="true" work-time="10.0" skill-required="2" frame="array frame" >
			<part name="solar panel" number="6" />
			<part name="power cable" number="2" />
			<part name="small motor" number="2" />			
			<part name="electrical wire" number="20" />
			<part name="wire connector" number="20" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</building>
		
		<building name="solar thermal array" width="5.0" length="10.0" base-level="0" constructable="true" 
		 salvagable="true" work-time="15.0" skill-required="3" frame="array frame" >
			<resource name="water" amount="200.0" />
			<part name="solar parabolic mirror" number="3" />
			<part name="power cable" number="2" />
			<part name="glass tube" number="6" />
			<part name="steel pipe" number="10" />
			<part name="small motor" number="2" />
			<part name="heat pump" number="1" />
			<part name="water pump" number="2" />
			<part name="electrical wire" number="20" />
			<part name="wire connector" number="20" />
			<part name="water tank" number="1" />			
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</building>
		
		<building name="methane power generator" width="5.0" length="5.0" base-level="0" constructable="true" 
		 salvagable="true" work-time="10.0" skill-required="3" frame="small steel frame" >
			<part name="fuel cell stack" number="12" />
			<part name="valve" number="6" />
			<part name="gasket" number="6" />
			<part name="plastic tubing" number="6" />
			<part name="power cable" number="6" />
			<part name="electrical wire" number="20" />
			<part name="wire connector" number="20" />
			<part name="fuel tank" number="5" />		
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</building>
		
		<building name="concrete storage bin" width="2.0" length="3.0" base-level="0" constructable="true" 
		 salvagable="true" work-time=".5" skill-required="1" frame="brick bin frame" />
		
		<building name="cement storage bin" width="2.0" length="3.0" base-level="0" constructable="true" 
		 salvagable="true" work-time=".5" skill-required="1" frame="brick bin frame" />
		
		<building name="mortar storage bin" width="2.0" length="3.0" base-level="0" constructable="true" 
		 salvagable="true" work-time=".5" skill-required="1" frame="brick bin frame" />
		
		<building name="lime storage bin" width="2.0" length="3.0" base-level="0" constructable="true" 
		 salvagable="true" work-time=".5" skill-required="1" frame="brick bin frame" />
		
		<building name="carbon storage bin" width="2.0" length="3.0" base-level="0" constructable="true" 
		 salvagable="true" work-time=".5" skill-required="1" frame="brick bin frame" />
		
		<building name="regolith storage bin" width="2.0" length="3.0" base-level="0" constructable="true" 
		 salvagable="true" work-time=".5" skill-required="1" frame="brick bin frame" />
		
		<building name="sand storage bin" width="2.0" length="3.0" base-level="0" constructable="true" 
		 salvagable="true" work-time=".5" skill-required="1" frame="brick bin frame" >
			<resource name="concrete" amount="10.0" />
		</building>
		
		<building name="ice storage bin" width="2.0" length="3.0" base-level="0" constructable="true" 
		 salvagable="true" work-time=".5" skill-required="1" frame="brick bin frame" >
			<resource name="concrete" amount="10.0" />
		</building>
		
		<building name="manufacturing shed" width="5.0" length="5.0" base-level="-1" constructable="true" 
		 salvagable="true" work-time="20.0" skill-required="3" frame="small brick shed frame" >
			<resource name="cement" amount="20.0" />
			<part name="steel pipe" number="3" />
			<part name="plastic pipe" number="10" />
			<part name="valve" number="10" />
			<part name="gasket" number="10" />
			<part name="plastic tubing" number="10" />
			<part name="power cable" number="10" />
			<part name="electrical wire" number="50" />
			<part name="wire connector" number="50" />
			<part name="epoxy resin bottle" number="25" />
			<part name="small motor" number="1" />
			<part name="brick" number="100" />
			<part name="gas tank" number="3" />		
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</building>

		<building name="bunkhouse" width="5.0" length="5.0" base-level="-1" constructable="true" 
		 salvagable="true" work-time="20.0" skill-required="3" frame="small brick shed frame" >
			<part name="steel pipe" number="3" />
			<part name="plastic pipe" number="4" />
			<part name="valve" number="5" />
			<part name="gasket" number="5" />
			<part name="plastic tubing" number="3" />
			<part name="power cable" number="1" />
			<part name="electrical wire" number="10" />
			<part name="wire connector" number="10" />
			<part name="epoxy resin bottle" number="25" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</building>
		
		<building name="large sabatier processor" width="5.0" length="5.0" base-level="0" constructable="true" 
		 salvagable="true" work-time="10.0" skill-required="3" frame="small steel frame" >
			<resource name="nickel" amount="1.0" />
			<part name="valve" number="6" />
			<part name="gasket" number="6" />
			<part name="small motor" number="1" />
			<part name="plastic tubing" number="6" />
			<part name="power cable" number="1" />
			<part name="electrical wire" number="5" />
			<part name="wire connector" number="5" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</building>
		
		<building name="medium battery array" width="5.0" length="10.0" base-level="0" constructable="true" 
		 salvagable="true" work-time="10.0" skill-required="2" frame="array frame" >
			<part name="rover battery" number="10" />
			<part name="fiberglass cloth" number="10" />
			<part name="power cable" number="2" />
			<part name="electrical wire" number="20" />
			<part name="wire connector" number="20" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</building>
		
		<!-- Lander hab building project for refitting or salvaging. -->
		<building name="lander hab" width="9.0" length="9.0" base-level="0" constructable="true" 
		 salvagable="true" work-time="100.0" skill-required="2" frame="round hab frame" >
			<resource name="polyester resin" amount="25.0" />
			<resource name="styrene" amount="15.0" />
			<resource name="polyethylene" amount="50.0" />
			<part name="steel sheet" number="10" />
			<part name="aluminum sheet" number="10" />
			<part name="plastic sheet" number="5" />
			<part name="fiberglass" number="5" />
			<part name="plastic pipe" number="7" />
			<part name="valve" number="5" />
			<part name="electrical wire" number="25" />
			<part name="wire connector" number="25" />
			<part name="gas tank" number="5" />	
			<part name="fuel tank" number="1" />	
			<part name="water tank" number="1" />						
		</building>
		
		<!-- Storage hab building project that is a modified lander hab. -->
		<building name="storage hab" width="9.0" length="9.0" base-level="0" constructable="true" 
		 salvagable="true" work-time="100.0" skill-required="2" frame="round hab frame" >
			<resource name="polyester resin" amount="5.0" />
			<resource name="styrene" amount="3.0" />
			<resource name="polyethylene" amount="20.0" />
			<part name="steel sheet" number="20" />
			<part name="aluminum sheet" number="15" />
			<part name="plastic sheet" number="20" />
			<part name="fiberglass" number="10" />
			<part name="fiberglass cloth" number="10" />
			<part name="plastic pipe" number="15" />
			<part name="valve" number="15" />
			<part name="electrical wire" number="15" />
			<part name="wire connector" number="15" />
		</building>
		
		<!-- Research hab building project that is a modified lander hab. -->
		<building name="research hab" width="9.0" length="9.0" base-level="0" constructable="true" 
		 salvagable="true" work-time="100.0" skill-required="2" frame="round hab frame" >
			<resource name="polyester resin" amount="25.0" />
			<resource name="styrene" amount="15.0" />
			<resource name="polyethylene" amount="50.0" />
			<part name="steel sheet" number="10" />
			<part name="aluminum sheet" number="10" />
			<part name="plastic sheet" number="5" />
			<part name="fiberglass" number="5" />
			<part name="plastic pipe" number="7" />
			<part name="valve" number="5" />
			<part name="electrical wire" number="25" />
			<part name="wire connector" number="25" />
		</building>
		
		<!-- Residential hab building project that is a modified lander hab. -->
		<building name="residential hab" width="9.0" length="9.0" base-level="0" constructable="true" 
		 salvagable="true" work-time="50.0" skill-required="2" frame="round hab frame" >
			<resource name="polyester resin" amount="25.0" />
			<resource name="styrene" amount="15.0" />
			<resource name="polyethylene" amount="50.0" />
			<part name="steel sheet" number="10" />
			<part name="aluminum sheet" number="10" />
			<part name="plastic sheet" number="5" />
			<part name="fiberglass" number="5" />
			<part name="plastic pipe" number="3" />
			<part name="valve" number="3" />
			<part name="electrical wire" number="10" />
			<part name="wire connector" number="10" />
		</building>
		
		<!-- Medical hab building project that is a modified lander hab. -->
		<building name="medical hab" width="9.0" length="9.0" base-level="0" constructable="true" 
		 salvagable="true" work-time="100.0" skill-required="2" frame="round hab frame" >
			<resource name="polyester resin" amount="25.0" />
			<resource name="styrene" amount="15.0" />
			<resource name="polyethylene" amount="50.0" />
			<part name="steel sheet" number="10" />
			<part name="aluminum sheet" number="10" />
			<part name="plastic sheet" number="5" />
			<part name="fiberglass" number="5" />
			<part name="plastic pipe" number="7" />
			<part name="valve" number="5" />
			<part name="electrical wire" number="25" />
			<part name="wire connector" number="25" />
		</building>
		
		<!-- Machinery hab building project that is a modified lander hab. -->
		<building name="machinery hab" width="9.0" length="9.0" base-level="0" constructable="true" 
		 salvagable="true" work-time="100.0" skill-required="2" frame="round hab frame" >
			<resource name="polyester resin" amount="25.0" />
			<resource name="styrene" amount="15.0" />
			<resource name="polyethylene" amount="50.0" />
			<part name="steel sheet" number="10" />
			<part name="aluminum sheet" number="10" />
			<part name="plastic sheet" number="5" />