<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE crop-configuration [
	<!ELEMENT crop-configuration (carbon-dioxide-consumption-rate, oxygen-consumption-rate, water-consumption-rate, watt-to-photon-conversion-ratio, category-list, crop-list)>
	<!ELEMENT carbon-dioxide-consumption-rate EMPTY>
	<!ATTLIST carbon-dioxide-consumption-rate value CDATA #REQUIRED>
	<!ELEMENT oxygen-consumption-rate EMPTY>
	<!ATTLIST oxygen-consumption-rate value CDATA #REQUIRED>
	<!ELEMENT water-consumption-rate EMPTY>
	<!ATTLIST water-consumption-rate value CDATA #REQUIRED>
	<!ELEMENT watt-to-photon-conversion-ratio EMPTY>
	<!ATTLIST watt-to-photon-conversion-ratio value CDATA #REQUIRED>

	<!ELEMENT category-list (category*)>
	<!ELEMENT category (phase*)>
	<!ATTLIST category name CDATA #REQUIRED>
	<!ATTLIST category description CDATA #REQUIRED>
	<!ATTLIST category needs-light CDATA #IMPLIED>

	<!ELEMENT phase EMPTY>
	<!ATTLIST phase name CDATA #REQUIRED>
	<!ATTLIST phase work-required CDATA #REQUIRED>
	<!ATTLIST phase growth-perc CDATA #REQUIRED>

	<!ELEMENT crop-list (crop*)>
	<!ELEMENT crop EMPTY>
	<!ATTLIST crop name CDATA #REQUIRED>
	<!ATTLIST crop growing-sols CDATA #REQUIRED>
	<!ATTLIST crop crop-category CDATA #REQUIRED>
	<!ATTLIST crop life-cycle CDATA #IMPLIED>
	<!ATTLIST crop edible-biomass CDATA #REQUIRED>
	<!ATTLIST crop edible-water-content CDATA #REQUIRED>
	<!ATTLIST crop inedible-biomass CDATA #REQUIRED>
	<!ATTLIST crop daily-PAR CDATA #REQUIRED>
	<!ATTLIST crop seed-name CDATA #IMPLIED>
]>

<!-- 

	Please read References 1 to 25 at the bottom 
	
	In mars-sim, there are 14 crop-categories:

	roots
	tubers
	corms
	stems
	leaves
	bulbs
	herbs
	fruits
	flowers
	seeds
	legumes (peanut, peas, soybean, kidney bean)
	grains ( rice, quinoa, wheat)
	grasses
	fungi
	(may be in future : spices)

-->

<crop-configuration>

	<!-- The average amount of carbon dioxide (kg) needed by a crop per square
	     meter area during the day [kg/m2/sol] -->
	<!-- Default: .2 -->
	<carbon-dioxide-consumption-rate value =".2" />

	<!-- The average amount of oxygen (kg) needed by a crop per square meter
	     area during the night -->
	<!-- Default: .1 -->
	<oxygen-consumption-rate value=".1" />

	<!-- The average amount of water (kg) consumed by a crop per square meter
	     area in each Martian Sol [kg/m2/sol]
	Note : KSC has daily water makeup requirements of 7 to 10 L/sq m/day
	depending on type and maturity of the crop -->
	<!-- Default: 3 -->
	<water-consumption-rate value="3" />

	<!-- The ratio of measured irradiance [ Wm^-2 to PPF on Mars. Useful for
	     calculating the instantaneous PAR in Crop.java -->
	<!-- see https://physics.stackexchange.com/questions/52487/photometer-measured-irradiance-l-converted-to-photon-rate -->
    <!-- Default: 4.568 on Mars in the unit of [(umol/s/m^2) / (W/m^2)] vs. 4.609 on Earth -->
	<watt-to-photon-conversion-ratio value="4.568" />


	<!-- Phenological growth stages of various crop categories -->

	<category-list>
		<category name="Roots" description="Roots are the underground part of a plant that absorbs water and minerals from the soil.">	
			<phase name="Incubation" work-required="1" growth-perc="0" />
			<phase name="Planting" work-required="0.5" growth-perc="1" />
			<phase name="Sprouting" work-required="1" growth-perc="5" />
			<phase name="Leaf Development" work-required="1" growth-perc="39" />
			<phase name="Root Development" work-required="1" growth-perc="40" />
			<phase name="Maturation" work-required="1" growth-perc="10" />
			<phase name="Harvesting" work-required="0.5" growth-perc="5" />
			<phase name="Finished" work-required="0.5" growth-perc="0" />
		</category>
		<category name="Grasses" description="Grasses are monocotyledonous, usually herbaceous plants with narrow leaves growing from the base.">
			<phase name="Incubation" work-required="1" growth-perc="0" />
			<phase name="Planting" work-required="0.5" growth-perc="1" />
			<phase name="Germination" work-required="1" growth-perc="5" />
			<phase name="Tillering" work-required="1" growth-perc="39" />
			<phase name="Grand Growth" work-required="1" growth-perc="40" />
			<phase name="Maturation" work-required="1" growth-perc="10" />
			<phase name="Harvesting" work-required="0.5" growth-perc="5" />
			<phase name="Finished" work-required="0.5" growth-perc="0" />
		</category>
		<category name="Grains" description="Grains are small, hard, dry seeds, with or without attached hulls or fruit layers, harvested for human or animal consumption.">
			<phase name="Incubation" work-required="1" growth-perc="0" />
			<phase name="Planting" work-required="0.5" growth-perc="1" />
			<phase name="Germination" work-required="1" growth-perc="9" />
			<phase name="Tillering" work-required="1" growth-perc="20" />
			<phase name="Stem Elongation" work-required="1" growth-perc="15" />
			<phase name="Flowering" work-required="1" growth-perc="20" />
			<phase name="Milk Development" work-required="1" growth-perc="10" />
			<phase name="Dough Development" work-required="1" growth-perc="10" />
			<phase name="Maturation" work-required="1" growth-perc="10" />
			<phase name="Harvesting" work-required="0.5" growth-perc="5" />
			<phase name="Finished" work-required="0.5" growth-perc="0" />
		</category>
		<category name="Bulbs" description="Bulbs are a short stem with fleshy leaves or leaf bases that function as food storage organs during dormancy.">
			<phase name="Incubation" work-required="1" growth-perc="0" />
			<phase name="Planting" work-required="0.5" growth-perc="1" />
			<phase name="Sprouting" work-required="1" growth-perc="5" />
			<phase name="Post Emergence" work-required="1" growth-perc="15" />
			<phase name="Leafing" work-required="1" growth-perc="29" />
			<phase name="Bulb Initiation" work-required="1" growth-perc="35" />
			<phase name="Maturation" work-required="1" growth-perc="10" />
			<phase name="Harvesting" work-required="0.5" growth-perc="5" />
			<phase name="Finished" work-required="0.5" growth-perc="0" />
		</category>
		<category name="Corms" description="Corms are a short, vertical, swollen underground plant stem that serves as a storage organ used by some plants to survive winter or other adverse conditions.">
			<phase name="Incubation" work-required="1" growth-perc="0" />
			<phase name="Planting" work-required="0.5" growth-perc="1" />
			<phase name="Sprouting" work-required="1" growth-perc="20" />
			<phase name="Vegetative Development" work-required="1" growth-perc="20" />
			<phase name="Flowering" work-required="1" growth-perc="15" />
			<phase name="Replacement Corms Development" work-required="1" growth-perc="30" />
			<phase name="Anthesis" work-required="1" growth-perc="9" />
			<phase name="Harvesting" work-required="0.5" growth-perc="5" />
			<phase name="Finished" work-required="0.5" growth-perc="0" />
		</category>
		<category name="Fruits" description="Fruits are the mature ovary of a flowering plant, usually containing seeds.">
			<phase name="Incubation" work-required="1" growth-perc="0" />
			<phase name="Planting" work-required="0.5" growth-perc="1" />
			<phase name="Germination" work-required="1" growth-perc="5" />
			<phase name="Vegetative Development" work-required="1" growth-perc="30" />
			<phase name="Flowering" work-required="1" growth-perc="25" />
			<phase name="Fruiting" work-required="1" growth-perc="24" />
			<phase name="Maturation" work-required="1" growth-perc="10" />
			<phase name="Harvesting" work-required="0.5" growth-perc="5" />
			<phase name="Finished" work-required="0.5" growth-perc="0" />
		</category>
		<category name="Herbs" description="Herbs are plants with savory or aromatic properties that are used for flavoring and garnishing food, medicinal purposes, or for fragrances.">
			<phase name="Incubation" work-required="1" growth-perc="0" />
			<phase name="Planting" work-required="0.5" growth-perc="1" />
			<phase name="Germination" work-required="1" growth-perc="9" />
			<phase name="Foilage" work-required="1" growth-perc="50" />
			<phase name="Flowering" work-required="1" growth-perc="20" />
			<phase name="Seed Fill" work-required="1" growth-perc="5" />
			<phase name="Pod Maturing" work-required="1" growth-perc="10" />
			<phase name="Harvesting" work-required="0.5" growth-perc="5" />
			<phase name="Finished" work-required="0.5" growth-perc="0" />
		</category>
		<category name="Leaves" description="Leaves are the main organs of photosynthesis and transpiration in higher plants.">
			<phase name="Incubation" work-required="1" growth-perc="0" />
			<phase name="Planting" work-required="0.5" growth-perc="1" />
			<phase name="Germination" work-required="1" growth-perc="5" />
			<phase name="Post Emergence" work-required="1" growth-perc="5" />
			<phase name="Head Development" work-required="1" growth-perc="39" />
			<phase name="50% Head Size Reached" work-required="1" growth-perc="35" />
			<phase name="Maturation" work-required="1" growth-perc="10" />
			<phase name="Harvesting" work-required="0.5" growth-perc="5" />
			<phase name="Finished" work-required="0.5" growth-perc="0" />
		</category>
		<category name="Legumes" description="Legumes are plants that bear fruit in the form of pods enclosing the seeds.">
			<phase name="Incubation" work-required="1" growth-perc="0" />
			<phase name="Planting" work-required="0.5" growth-perc="1" />
			<phase name="Germination" work-required="1" growth-perc="5" />
			<phase name="Leafing" work-required="1" growth-perc="30" />
			<phase name="Flowering" work-required="1" growth-perc="25" />
			<phase name="Seed Fill" work-required="1" growth-perc="20" />
			<phase name="Pod Maturing" work-required="1" growth-perc="14" />
			<phase name="Harvesting" work-required="0.5" growth-perc="5" />
			<phase name="Finished" work-required="0.5" growth-perc="0" />
		</category>
		<category name="Stems" description="Stems are the main body or stalk of a plant or shrub, typically rising above ground but occasionally subterranean.">
			<phase name="Incubation" work-required="1" growth-perc="0" />
			<phase name="Planting" work-required="0.5" growth-perc="1" />
			<phase name="Early Vegetative" work-required="1" growth-perc="15" />
			<phase name="Mid Vegetative" work-required="1" growth-perc="15" />
			<phase name="Stem Elongation" work-required="1" growth-perc="34" />
			<phase name="Early Bulking Up" work-required="1" growth-perc="10" />
			<phase name="Mid Bulking Up" work-required="1" growth-perc="10" />
			<phase name="Late Bulking Up" work-required="1" growth-perc="10" />
			<phase name="Harvesting" work-required="0.5" growth-perc="5" />
			<phase name="Finished" work-required="0.5" growth-perc="0" />
		</category>
		<category name="Tubers" description="Tubers are the thickened part of an underground stem or rhizome that stores nutrients.">
			<phase name="Incubation" work-required="1" growth-perc="0" />
			<phase name="Planting" work-required="0.5" growth-perc="1" />
			<phase name="Sprouting" work-required="1" growth-perc="10" />
			<phase name="Leaf Development" work-required="1" growth-perc="15" />
			<phase name="Tuber Initiation" work-required="1" growth-perc="20" />
			<phase name="Tuber Filling" work-required="1" growth-perc="35" />
			<phase name="Maturation" work-required="1" growth-perc="14" />
			<phase name="Harvesting" work-required="0.5" growth-perc="5" />
			<phase name="Finished" work-required="0.5" growth-perc="0" />
		</category>
		<category name="Flowers" description="For flowers that do NOT have seeds. Flowers can be considered the seed-bearing part of a plant, consisting of reproductive organs that are typically surrounded by brightly colored petals and a green calyx.">
			<phase name="Incubation" work-required="1" growth-perc="0" />
			<phase name="Planting" work-required="0.5" growth-perc="1" />
			<phase name="Germination" work-required="1" growth-perc="5" />
			<phase name="Seedling Development" work-required="1" growth-perc="10" />
			<phase name="Vegetative Growth" work-required="1" growth-perc="44" />
			<phase name="Budding" work-required="1" growth-perc="15" />
			<phase name="Flowering" work-required="1" growth-perc="10" />
			<phase name="Ripening" work-required="1" growth-perc="10" />
			<phase name="Harvesting" work-required="0.5" growth-perc="5" />
			<phase name="Finished" work-required="0.5" growth-perc="0" />
		</category>
		<category name="Fungi" description="Fungi are a group of spore-producing organisms that feed on organic matter."
				needs-light="false">
			<phase name="Incubation" work-required="1" growth-perc="0" />
			<phase name="Planting" work-required="0.5" growth-perc="1" />
			<phase name="Spore Germination" work-required="1" growth-perc="5" />
			<phase name="Mycelium Formation" work-required="1" growth-perc="79" />
			<phase name="Fruiting Body Development" work-required="1" growth-perc="10" />
			<phase name="Harvesting" work-required="0.5" growth-perc="5" />
			<phase name="Finished" work-required="0.5" growth-perc="0" />
		</category>
		<category name="Seeds" description="For flowers that DO have seeds. Seeds are the part of a flowering plant that typically contains an embryo and is capable of developing into a new plant.">
		<phase name="Incubation" work-required="1" growth-perc="0" />
			<phase name="Planting" work-required="0.5" growth-perc="1" />
			<phase name="Germination" work-required="1" growth-perc="5" />
			<phase name="Seedling Development" work-required="1" growth-perc="25" />
			<phase name="Vegetative Growth" work-required="1" growth-perc="45" />
			<phase name="Flowering" work-required="1" growth-perc="10" />						
			<phase name="Seed Head Development" work-required="1" growth-perc="4" />
			<phase name="Seed Growing" work-required="1" growth-perc="4" />
			<phase name="Dispersing Seeds" work-required="1" growth-perc="1" />
			<phase name="Harvesting" work-required="0.5" growth-perc="5" />
			<phase name="Finished" work-required="0.5" growth-perc="0" />
		</category>
	</category-list>

	<crop-list>

		<!-- Note : see Reference 7
		
			photosynthetic photon flux (PPF) for the (400-700) nm waveband was in umol / m^2 / s."

			Photosynthetically Active Radiation (PAR) refers to the range of light wavelengths between 
			400 and 700 nanometers (nm) that are used by plants for photosynthesis.
			
 			This range corresponds to the visible light spectrum, which includes blue, green, and red 
 			wavelengths.
 			
 			PAR is measured in units such as micromoles of quanta per second per square meter [µmol / s / m^2].
 			
			growing-sols : # of sols
			crop-category : the type of crop
			edible-biomass : [ kg / m^2 / year ]
			edible-water-content : in proportion of 1 (1 is 100%)
			inedible-biomass :  [ kg / m^2 / year ]
			daily-PAR : [ mol / m^2 / day ], not [ umol / m^2 / s ]	
			
			On Earth, 1 W/m² ≈ 4.609 μmol/m²/s comes from the Plant Growth Chamber Handbook (chapter 1, radiation; 
			https://www.controlledenvironments.org/wp-content/uploads/sites/6/2017/06/Ch01.pdf)
			1/4.609 > 0.2169668
			
			On Mars, 1 W/m² ≈ 4.568 μmol/m²/s
			1/4.568 > 0.2189141856
				
			Since only about 45% of the energy of solar radiation is actually in the 400 - 700 nm range, 
			the conversion of TOTAL solar radiation to PAR is ~2.0556, rather than 4.568.
			.45 * 4.568 = 2.0556
			1/2.0556 > 0.4864759681
			
			1 µmol of photons in the PAR range is approximately equivalent to 0.275 joules (J) of energy.
 
 			To convert this to watts, you would divide by the time in seconds. Therefore, 1 µmol/s 
 			(micromole per second) is approximately 0.275 W.
			
			
			
			
			In general, PAR levels are highest during the summer at mid-day, reaching values of 2,000 to 3,000
	    	millimoles per square meter.
	    	 	
	    	1 t/h or 1 tonnes per hectare ->  0.1 kilogram per square meter.
 			Conversely, 1 kilogram per square meter -> 10 tonnes per hectare.
	    	
	   		1 tonne per acre is approximately equal to 0.2471 kilograms per square meter.
	   		1 kg / m2 -> 4.0469 t per acre

			1 tonne per hectare (t/ha) is equivalent to 0.446 US tons per acre
			
			life-cycle : perennial/annual/biennials
			1. A perennial is a plant that lives for more than two years, as opposed to 
			2. annuals, which complete their life cycle in one year, and 
			3. biennials, which bloom in their second year and die.
			
			Perennials can be categorized into woody plants and herbaceous perennials.
			Woody plants include trees and shrubs, while herbaceous perennials grow 
			and bloom during spring and summer, die back in fall and winter, and 
			return in the spring from their rootstock.
		-->

		<!-- Future additions : 
			1. asparagus, basil, hops, ...
		-->
		
		<!-- https://www.researchgate.net/publication/262910301_Phenological_growth_stages_of_edible_asparagus_Asparagus_officinalis_Codification_and_description_according_to_the_BBCH_scale 
		-->

		<crop name="Basil" growing-sols="27" crop-category="leaves" life-cycle="biennial"
	    	edible-biomass="1.1" edible-water-content=".2" inedible-biomass="0.2" daily-PAR="17.28" />

		<!-- 
			Grown in a floating hydroponic system, basil had a crop cycle of 27 days.
			Shoot FW yield : 1.1 kg / m2
			Root FW 9 g/m2)
		-->

	   	<crop name="Blueberry" growing-sols="300" crop-category="fruits" life-cycle="perennial"
	    	edible-biomass="1.5" edible-water-content=".87" inedible-biomass="4.5" daily-PAR="25.92" />
	    	
	    <!-- 
			Assume 15 t/ha -> 1.5 kg/m²
			
	    	Assume this blueberry variant takes half the time (600 days -> 300 days)
	    	
	    	average yields of mature blueberry plantings range from 7 to 10 tons per acre for early-season 
	    	cultivars such as ‘Duke’, and even greater in many mid- and late-season cultivars such as ‘Liberty’, ‘Legacy’, ‘Elliott’, and ‘Aurora’.

	    	
	    	http://blueberries.ces.ncsu.edu/wp-content/uploads/2012/10/evaluating-the-profitability-of-blueberry-production.pdf
	    	
	    	The expected yield pattern over the 20-year life of the planting for various
			assumptions of soil quality and irrigation. The irrigated planting on good blueberry soil reaches a peak
			production of 8,000 pounds per acre  in the seventh through ninth years or 3,000 pounds per acre higher
			than a similar planting without irrigation. Peak yields are projected to be lower on marginal soils reaching
			a maximum yield of 6,000 pounds per acre on an irrigated planting, which is double the yield of a planting
			without irrigation. 

			8,000 pounds per acre -> 0.897 kg/m2
	    	
	    	http://homeguides.sfgate.com/long-blueberry-plants-produce-60750.html

	    	http://www.offthegridnews.com/survival-gardening-2/4-perennial-berries-you-can-plant-once-and-enjoy-for-a-lifetime/

	    	For blueberries to thrive, three conditions must be met: adequate water, weather that is not blazingly hot,	
	    	and the right soil. You may have heard that blueberries require acidic soil, and this is not an exaggeration.
	    	They thrive in a pH around four.
	    	
	    -->
	    


		<crop name="Cabbage" growing-sols="85" crop-category="leaves"  life-cycle="annual"
	    	edible-biomass="5" edible-water-content=".92" inedible-biomass=".5" daily-PAR="17.28" />
		<!--
			assuming 50 t/ha/yr -> 5 kg/m²/yr
			assuming all 70 is edible biomass		
			
			The average cabbage yield is 30-70 tons per hectare
			
			
			https://www.fao.org/land-water/databases-and-software/crop-information/cabbage/en/
			
			Under rainfed conditions, yields of 25 to 35 ton/ha fresh heads are normal, with a maximum of
			about 50 ton/ha when sprayed and well-fertilized. Under ideal climatic conditions and good 
			irrigation and crop management, yields can be as high as 85 ton/ha. 
			
			The utilization efficiency for harvested yield (Ey) for heads is about 12 to 20 kg/m3.

			The average water content of cabbage heads is about 90 percent, with a high vitamin B, C 
			and calcium and phosphorous content. Smaller heads of poor quality are produced when the 
			crop is grown under limited water supply, particularly during the later part of the 
			growing period.



		http://www.ehow.com/facts_7732455_life-cycle-cabbage-plant.html

		Growing Environment
		Cabbage plants prefer summers with temperatures ranging from 70 to 85 degrees Fahrenheit,
		moist soil and full sun. Transplants benefit from a starter solution that is high in phosphorus,
		low in nitrogen;
		-->

		<crop name="Carrot"	growing-sols="75" crop-category="roots" life-cycle="biennial"
	    	edible-biomass="12"	edible-water-content=".88" inedible-biomass="59.87" daily-PAR="32.4"
	    	/>

		<!--
			
		Assume 120 t/ha -> 12 kg/sqm
			
		https://www.revistas.ufg.br/pat/article/download/42449/22580
		31 T to 120 T/ha

		http://smallfarms.oregonstate.edu/sites/default/files/growth_stage_descriptions_online_2014-08-25.pdf
		stages: seedling emergence, leaving, root development, harvest

		-->

		<crop name="Celery" growing-sols="75" crop-category="stems" life-cycle="biennial"
	    	edible-biomass="3.5" edible-water-content=".90" inedible-biomass="0.5" daily-PAR="17.28" />

	    <!-- 
			
			Assume 35 t/ha -> 3.5 kg/sqm
			
			Celery Sampling & Growth Stages at http://agvita.com.au/pdf/sampling/Celery_GS_V2.pdf 
	    
	    
	    Generally, the plants grown for stalks are ready to be harvested 3-4 months after planting, 
	    by the time they have reached the preferable marketable size. An average-good yield for 
	    fresh market celery crops is around 20-35 tonnes per hectare (8-14 t/acre).
	    
 		This yield range represents the biomass of celery at harvest, focusing on the stalks, 
 		which are the primary part harvested.
	    
	    -->

		<crop name="Cilantro" growing-sols="30" crop-category="herbs" life-cycle="annual"
	    	edible-biomass="2.5" edible-water-content=".76" inedible-biomass="0.5" daily-PAR="34.56" 
	    	seed-name="Coriander" />
	    <!-- https://rennieorchards.com/is-cilantro-perennial/
	    
	    Annual coastal production average from 8 to 11 tonnes per acres (18 to 25 t/ha)
	    
		-->

		<crop name="Corn" growing-sols="65" crop-category="grains" life-cycle="annual"
	    	edible-biomass="0.83" edible-water-content=".76" inedible-biomass="3.0" daily-PAR="34.56" />

		<!--
		http://lib.dr.iastate.edu/cgi/viewcontent.cgi?article=4354&context=etd
		Corn stover is a broad term which describes all of the above ground biomass
		from the corn crop except the grain. This biomass is comprised of structural
		components including stalks, leaves, tassel, husk, and cob. The U.S. Department of
		Energy estimates that over 76 million metric tons of corn stover are available from the
		roughly 28 million hectares of corn produced each year (Perlack, 2005).

		Worldwide, with a yield of over 5 T/ha . Production can be significantly higher in certain regions of the world;
		2009 forecasts for production in Iowa were 11614 kg/ha

		Use (11.6 + 5)/2 = 8.30 T/ha
		8.30*100/65 = 12.77 g/m2/d

		http://www.ent.iastate.edu/pest/cornborer/stages-corn-development
		http://www.ent.iastate.edu/pest/cornborer/insect/damage

		Corn Growth and Development, https://graincrops.ca.uky.edu/files/corngrowthstages_2011.pdf
		Chad Lee, Univ. of Kentucky, 2005-2011

		CORN DEVELOPMENT AND KEY GROWTH STAGES
		http://publications.tamu.edu/CORN_SORGHUM/PUB_Corn%20Development%20and%20Key%20Growth%20Stages.pdf
		Reproductive stage :
		silking, blister, milk, dough, dent, 1/2 maturity, black layer

		Field corn vs. Sweet corn
		Although field corn is used mostly to create other products, sweet corn can be used as well.
		Plastics are manufactured from 		both types of corn to replace petroleum-based products.
		These include batteries, packaging materials, plastic silverware and other plastic products
		(such as skin and hair care bottles), toothpaste, candles, shampoo and dozens of others.
		A corn-based fuel for transportation, ethanol, is added to gasoline and is sold at many gas stations.

 		-->

	   	<crop name="Cranberry" growing-sols="150" crop-category="fruits" life-cycle="perennial"
	    	edible-biomass="1.12" edible-water-content=".87" inedible-biomass="10" daily-PAR="25.92" />
	    	<!-- 
				
			11.2 tonnes/hectare
			
	    	Assume this cranberry variant takes half the time (300 days -> 150 days)
	    	
	    	http://www.umass.edu/cranberry/downloads/Homeowner's%20fact%20sheet%202010.pdf
	    	http://www.ecologynorth.ca/wp-content/uploads/2012/03/Stimulating-Commercial-Berry-Production-FINAL-FEB-2012.pdf
	    	Production from mature plants is about 11 tonnes per hectare.
	    	Well-managed bogs should produce 100 to 200 barrels of cranberries per acre,

	    	http://bioweb.uwlax.edu/bio203/2011/mullenba_brit/life.html
	    	“I will survive” is a true saying for the cranberry.  The cranberry lives year round.
	    	They survive through the cold winters, sweltering summers, and cool springs and falls.
	    	-->

	   	<crop name="Cucumber" growing-sols="60" crop-category="fruits" life-cycle="perennial"
	    	edible-biomass="1.8" edible-water-content=".90" inedible-biomass="18" daily-PAR="25.92" />
	    	<!--
				
			18,000 kg/ha -> 1.8 kg/m2
			
			
	    	http://www.sqm.com/en-us/productos/nutricionvegetaldeespecialidad/cultivos/pepino.aspx#tabs-2
	    	http://teca.fao.org/sites/default/files/technology_files/High%20yielding%20vegetable%20varieties.pdf

	    	The cucumber is a tropical perennial in zones 10 and warmer. In colder zones, it is grown as an annual.
	    	-->


		<crop name="Dandelion" growing-sols="90" crop-category="flowers" life-cycle="perennial"
	    	edible-biomass="1.11" edible-water-content=".4" inedible-biomass="0.1" daily-PAR="25" />
	    	
	    <!--	
			In future, separate the dandelion roots from dandelion leaves
			
			But now, assume their combined biomass yield is triple that of the root, thus .37 * 3 = 1.11
			
			Studies have shown that under experimental field conditions, the fresh root yield of wild Russian 
			dandelion (Taraxacum koksaghyz) ranged from 1.3 to 1.9 metric tons per hectare in one trial and 
			2.2 to 3.7 metric tons per hectare in another trial
			 
			The fresh root yield would range from approximately 0.13 to 0.19 kg/m² in the first trial and 
			0.22 to 0.37 kg/m² in the second trial.
			  
			Note: Harvest dandelion at 90 sols before seed-bearing phase because seeds are invasive and spread.
			
			use 'flowers', instead of 'seeds' as crop category since we do not intend to harvest seeds as food
			
			Dandelion is a perennial plant. It is a hardy perennial that is grown as an annual for its foliage 
			and as a biennial for its roots.
			
 			The plant has a strong, deep taproot that allows it to persist over the winter.
 			
 			Dandelion is a short-lived perennial that will grow just about anywhere, regardless of soil conditions.
 			
 			The plant is also described as a perennial with a stout taproot, is abundant everywhere but 
 			prefers chalks and loamy soils above pH 7.0.
 
			A flower head can produce up to 400 seeds but the average is 180. A plant may have
			a total of 2,000 to 12,000 seeds (Salisbury, 1961; Stevens, 1932), or even 23,456
			seeds (Stewart-Wade et al., 2002). The average seed number per plant is 2,720
			(Pawlowski et al., 1970). The 1,000 seed weight is given as 0.583 g (Bostock, 1978)
			and 0.620-0.640 g (Stevens, 1932). Seed weight may vary with the time of year it is
			produced. 
			
			The time from flowering to seed ripening takes about 9-12 days. At least 7
			days must elapse before seeds are likely to be viable. Ripe seed gave 90%
			germination but cut down flowering stems did not produce any viable seed (Gill,
			1938). 
 
	    	https://cals.cornell.edu/weed-science/weed-profiles/dandelion
	    	  	
	    	Seed weight: 0.34 mg (seeds produced in summer) to 0.54 mg (seeds produced in spring) (Martinkova et al. 2011, 
	    	Doisy et al. 2014, Milberg et al. 2000, Werle et al. 2014); 0.6 mg (Bostock 1978).
	    	
	    	Seeds will germinate at temperatures from 41 to 95 °F (5 to 35 °C), but percentage germination and speed of 
	    	germination are reduced at temperatures above 68 °F (20 °C) (Luo and Cardina 2012, Washitani 1984).  
	    	Germination is highest at alternating day/night temperatures of 59/41 °F (15/5 °C) and 77/59 °F (25/15 °C), 
	    	and reduced at 95/77 °F (35/25 °C) (Luo and Cardina 2012).
	    	
	    	Seed longevity: Seeds can last 1-5 years in the soil, but in normal agricultural conditions, only a few 
	    	survive to the next season (Stewart-Wade et al. 2002).  The overwhelming majority of seedlings come from 
	    	recently dispersed seeds (Hacault & Van Acker 2006).

			Seeds are killed by storage at 27 °C with 80% humidity.

			Emergence depth:  Emergence is not affected by depth between 0 and 0.8” (2 cm) but declines at progressively 
			greater depths.  No emergence occurs from seeds below 3” (8 cm).  Emergence from small root fragments can 
			occur from 2-4” (5-10 cm) of soil (Stewart-Wade et al. 2002). 
			
			Photosynthetic pathway:  C3 (Stewart-Wade et al. 2002).
			
			Response to shade:  Dandelion is shade tolerant (Stewart-Wade et al. 2002) and will grow even under 
			competitive crops like potato.
			
			Time from emergence to reproduction: Dandelions that have formed a strong taproot and 20 leaves (some of 
			which may have subsequently died) are usually ready to flower (Stewart-Wade et al. 2002).  Peak flowering 
			begins in mid-spring and continues for 2 to 6 weeks (Doll 2006, Honek et al. 2005), but can continue 
			throughout the year with a secondary peak in fall (Gray et al. 1973, Mann and Cavers 1979).  
			
			A few seeds may become viable as early as 3 days after the flowers wither and close, but most are not 
			viable until 6-8 days after flowering in the summer or about 10 days after flowering in the spring or 
			fall (Martinkova et al. 2011).
			
			The roots are used in medicine as a tonic and for their diuretic properties. Dandelion plants release 