<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE people-configuration [
	<!ELEMENT people-configuration (
	person-attributes,
	personality-types,
	training-list,
	country-list)>

	<!ELEMENT person-attributes (
	base-carrying-capacity,
	average-tall-height,
	average-short-height,
	average-high-weight,
	average-low-weight,
	low-activity-metaboic-load-o2-consumption-rate,
	nominal-activity-metaboic-load-o2-consumption-rate,
	high-activity-metaboic-load-o2-consumption-rate,
	co2-expelled-rate,
	water-consumption-rate,
	water-usage-rate,
	grey-to-black-water-ratio,
	dessert-consumption-rate,
	food-consumption-rate,
	oxygen-deprivation-time,
	water-deprivation-time,
	dehydration-start-time,
	food-deprivation-time,
	starvation-start-time,
	decompression-time,
	min-air-pressure,
	min-o2-partial-pressure,
	min-temperature,
	max-temperature,
	freezing-time,
	stress-breakdown-chance,
	high-fatigue-collapse-chance)
	>

	<!ELEMENT base-carrying-capacity EMPTY>
	<!ATTLIST base-carrying-capacity value CDATA #REQUIRED>

	<!ELEMENT average-tall-height EMPTY>
	<!ATTLIST average-tall-height value CDATA #REQUIRED>

	<!ELEMENT average-short-height EMPTY>
	<!ATTLIST average-short-height value CDATA #REQUIRED>

	<!ELEMENT average-high-weight EMPTY>
	<!ATTLIST average-high-weight value CDATA #REQUIRED>

	<!ELEMENT average-low-weight EMPTY>
	<!ATTLIST average-low-weight value CDATA #REQUIRED>

	<!ELEMENT low-activity-metaboic-load-o2-consumption-rate EMPTY>
	<!ATTLIST low-activity-metaboic-load-o2-consumption-rate value CDATA #REQUIRED>

	<!ELEMENT nominal-activity-metaboic-load-o2-consumption-rate EMPTY>
	<!ATTLIST nominal-activity-metaboic-load-o2-consumption-rate value CDATA #REQUIRED>

	<!ELEMENT high-activity-metaboic-load-o2-consumption-rate EMPTY>
	<!ATTLIST high-activity-metaboic-load-o2-consumption-rate value CDATA #REQUIRED>

	<!ELEMENT co2-expelled-rate EMPTY>
	<!ATTLIST co2-expelled-rate value CDATA #REQUIRED>

	<!ELEMENT water-consumption-rate EMPTY>
	<!ATTLIST water-consumption-rate value CDATA #REQUIRED>

	<!ELEMENT water-usage-rate EMPTY>
	<!ATTLIST water-usage-rate value CDATA #REQUIRED>

	<!ELEMENT grey-to-black-water-ratio EMPTY>
	<!ATTLIST grey-to-black-water-ratio value CDATA #REQUIRED>

	<!ELEMENT dessert-consumption-rate EMPTY>
	<!ATTLIST dessert-consumption-rate value CDATA #REQUIRED>

	<!ELEMENT food-consumption-rate EMPTY>
	<!ATTLIST food-consumption-rate value CDATA #REQUIRED>

	<!ELEMENT oxygen-deprivation-time EMPTY>
	<!ATTLIST oxygen-deprivation-time value CDATA #REQUIRED>

	<!ELEMENT water-deprivation-time EMPTY>
	<!ATTLIST water-deprivation-time value CDATA #REQUIRED>

	<!ELEMENT dehydration-start-time EMPTY>
	<!ATTLIST dehydration-start-time value CDATA #REQUIRED>

	<!ELEMENT food-deprivation-time EMPTY>
	<!ATTLIST food-deprivation-time value CDATA #REQUIRED>

	<!ELEMENT starvation-start-time EMPTY>
	<!ATTLIST starvation-start-time value CDATA #REQUIRED>

	<!ELEMENT decompression-time EMPTY>
	<!ATTLIST decompression-time value CDATA #REQUIRED>

	<!ELEMENT min-air-pressure EMPTY>
	<!ATTLIST min-air-pressure value CDATA #REQUIRED>

	<!ELEMENT min-o2-partial-pressure EMPTY>
	<!ATTLIST min-o2-partial-pressure value CDATA #REQUIRED>

	<!ELEMENT min-temperature EMPTY>
	<!ATTLIST min-temperature value CDATA #REQUIRED>

	<!ELEMENT max-temperature EMPTY>
	<!ATTLIST max-temperature value CDATA #REQUIRED>

	<!ELEMENT freezing-time EMPTY>
	<!ATTLIST freezing-time value CDATA #REQUIRED>

	<!ELEMENT stress-breakdown-chance EMPTY>
	<!ATTLIST stress-breakdown-chance value CDATA #REQUIRED>

	<!ELEMENT high-fatigue-collapse-chance EMPTY>
	<!ATTLIST high-fatigue-collapse-chance value CDATA #REQUIRED>

	<!ELEMENT gender-male-percentage EMPTY>
	<!ATTLIST gender-male-percentage value CDATA #REQUIRED>

	<!ELEMENT personality-types (mbti*)>

	<!ELEMENT mbti EMPTY>
	<!ATTLIST mbti type CDATA #REQUIRED>
	<!ATTLIST mbti percentage CDATA #REQUIRED>
	
	<!ELEMENT training-list (training*)>
	<!ELEMENT training (benefit*)>
	<!ATTLIST training name CDATA #REQUIRED>
	<!ELEMENT benefit EMPTY>
	<!ATTLIST benefit role CDATA #REQUIRED>
	<!ATTLIST benefit modifier CDATA #REQUIRED>

	<!ELEMENT country-list (country*)>
	<!ELEMENT country (first-name-list, last-name-list)>
	<!ATTLIST country name CDATA #REQUIRED>

	<!ELEMENT first-name-list (first-name*)>
	<!ELEMENT first-name EMPTY>
	<!ATTLIST first-name value CDATA #REQUIRED>
	<!ATTLIST first-name gender (male|female) #REQUIRED>

	<!ELEMENT last-name-list (last-name*)>
	<!ELEMENT last-name EMPTY>
	<!ATTLIST last-name value CDATA #REQUIRED>
]>

<people-configuration>
	<person-attributes>
		<!-- The base load-carrying capacity of an adult person in kg. Will be modified by age and attribute of a person -->
		<base-carrying-capacity value="30" />
		<!-- The upper average height of a person in cm -->
		<average-tall-height value="176.5" />
		<!-- The lower average height of a person in cm -->
		<average-short-height value="162.5" />
		<!-- The upper average weight of a person in kg -->
		<average-high-weight value="68.5" />
		<!-- The lower average weight of a person in kg -->
		<average-low-weight value="57.2" />

		<!-- The average amount of oxygen breathed in by a person on each Sol for
			low, nominal & high metabolic activities -->
		<!-- Default: 0.78, 0.84, 0.96 [in kg] -->
		<low-activity-metaboic-load-o2-consumption-rate
			value="0.78" />
		<nominal-activity-metaboic-load-o2-consumption-rate
			value="0.84" />
		<high-activity-metaboic-load-o2-consumption-rate
			value="0.96" />
		<!-- e.g. total surface requirement for a crew of 3 during a 500-day surface
			stay based on nominal activity is ~1260 kg of O2 -->

		<!-- The average amount of carbon dioxide expelled by a person on each Sol
			for high metabolic activities -->
		<!-- Default: 1.0433 [in kg/sol] -->
		<co2-expelled-rate value="1.0433" />
		<!--

		Note: this is in contrast with the value of 700 to 900 mL CO2 exhaled
			due to norminal activity from https://www.globe.gov/explore-science/scientists-blog/archived-posts/sciblog/index.html_p=183.html

		// NOTE: Assume the EVA Suit has pump system to vent out all CO2 to prevent the built-up.
		// The breath rate is 12 to 25 per minute.
		// Size of breath is 500 mL.
		// Percent CO2 exhaled is 4%.
		// CO2 per breath is approx 0.04g = 2g/L x 4% x 500mL.

		-->


		<!-- The normal average amount of water drank by a person on each sol -->
		<!-- Default: 2.5 -->
		<water-consumption-rate value="2.5" />

		<!-- The normal average amount (kg) of hygiene water (toilet, shower, clothing
			wash) toilet, etc.) by a person each martian sol -->
		<!-- This compares with ~288 kg water usage per person per day in US -->
		<!-- Note : 1 US gallon = 3.79 kg or liter (water) -->
		<!-- Instead of consuming an average of 50 liters to take a shower (typical
			on Earth), denizens of the ISS uses 4 liters to bathe. -->
		<!-- Default: 20.0 -->
		<water-usage-rate value="20.0" />

		<!-- The fictitious ratio denoting the amount of grey water and black water
			generated per unit water usage -->
		<!-- Default: 4.0. This translates to 80% grey water and 20% black water
			(OR 4 to 1) -->
		<grey-to-black-water-ratio value="4.0" />

		<!-- The normal average amount of dessert (kg) in dry weight eaten by a
			person on each Martian Sol -->
		<!-- Default: 0.3 dry Weight (arbitrary), note that beverage has arbitrary
			predefined weight -->
		<dessert-consumption-rate value="0.2" />

		<!-- The normal average amount of food (kg) in dry weight eaten by a person
			on each Martian Sol -->
		<!-- Default: 0.62 dry Weight -->
		<food-consumption-rate value="0.62" />

		<!-- TODO: account for carbohydrates & protein content 
		
			(1). http://settlement.arc.nasa.gov/75SummerStudy/Chapt3.html#Food
			
			A heavy workload requires about 3000 Cal/day...consist of 2000 g of water,
			470 g dry weight of various carbohydrates and fats, 60 to 70 g dry weight
			of proteins, and adequate quantities of various minerals and vitamins 
			
			(2). http://settlement.arc.nasa.gov/Contest/Results/96/winner/seis.html#HUMAN
			
			Food solids: 0.62Kg , Water in food: 1.15Kg 
			
			(3). Food energy per mass: http://en.wiki2.org/wiki/Food_energy
			a. Fats and ethanol have 37 and 29 kJ/g (8.8 and 6.9 kcal/g) b. Proteins
			and most carbohydrates have about 17 kJ/g (4.1 kcal/g) c. Notes: 1. Each
			meal is 0.62kg / 4 2. 
			
			Assume a daily intake of: 0.1 kg of fats, 0.4 kg of
			proteins and carbo, 0.12 of fibers and others, Daily intake : .1 * 1000 *
			33 kJ + .4 * 1000 * 17 kJ + ... = 10100 kJ or 2415.2 kcal 
			
			Each meal has 0.1550
			kg or 2525 kJ 1 kg ==> 16290.323 kJ FOOD_COMPOSITION_ENERGY_RATIO = 16290.323
			
			(4). A standard conversion in the Systeme Internation de'Unites is that one
			calorie equals 4.186 joules, which is how much energy is given off in heat
			to raise 1 kg of water 1 degree Celsius. 
			
			4.186 J = 1 cal OR 4.186 kJ = 1	Cal or 1 kcal 
			
			a). 1 small kilocalorie (kcal) is equal to 1 large food calorie	(Cal): 1 kcal = 1 Cal b). 
			
			1 small kilocalorie (kcal) is equal to 1000 small calories (cal): 1 kcal = 1000 cal -->

		<!-- Number of millisols a person can survive without oxygen -->
		<!-- Note: 1 millisol = 88.77 seconds -->
		<!-- Default: 3.38 -->
		<oxygen-deprivation-time value="3.38" />

		<!-- Number of sols a person can go without water before dying -->
		<!-- Default: 7.0 -->
		<water-deprivation-time value="7.0" />

		<!-- Number of sols without water before dehydration kicks in -->
		<!-- Default: 2.0 -->
		<dehydration-start-time value="3.0" />

		<!-- Number of sols a person can go without food before dying -->
		<!-- Default: 40.0 -->
		<food-deprivation-time value="40.0" />

		<!-- Number of sols without food before starvation kicks in -->
		<!-- Default: 7.0 -->
		<starvation-start-time value="7.0" />

		<!-- Number of millisols a person can survive in decompression -->
		<!-- Note: 1 millisol = 88.77 seconds -->
		<!-- Default: 10.0 ) -->
		<decompression-time value="10.0" />

		<!-- Minimum air pressure (kPa) a person can withstand without harm At least
			170 mb (2.5 psi, or 17.24 kPa) without a spacesuit, Note : 1kPa = 0.1450377
			psi see "How To Live On Mars" per Zubrin, P.91 -->
		<!-- Default: 17.24 -->
		<min-air-pressure value="17.24" />

		<!-- The absolute minimum oxygen partial pressure -->
		<!-- According to https://en.wikipedia.org/wiki/Mars_suit#Breathing for
			a space suit, the absolute minimum safe oxygen requirement is a partial pressure
			of 11.94 kPa (1.732 psi) -->
		<!-- Default: 11.94 -->
		<min-o2-partial-pressure value="11.94" />

		<!-- Minimum temperature (degrees celsius) a person can withstand without
			harm -->
		<!-- Default: 0 degrees celsius -->
		<min-temperature value="-20.0" />

		<!-- Maximum temperature (degrees celsius) a person can withstand without
			harm -->
		<!-- Default: 48 degrees celsius -->
		<max-temperature value="48.0" />

		<!-- Number of millisols a person can survive below minimum temperature -->
		<!-- Note: 1 millisol = 88.77 seconds -->
		<!-- Default: 25.0 -->
		<freezing-time value="250.0" />

		<!-- Base percent chance per millisol that a person at high stress will
			have a panic attack or depression. -->
		<!-- See medical complaint: "Panic Attack" and "Depression" in medical.xml. -->
		<!-- Default: 10 [in percentage] -->
		<stress-breakdown-chance value="10.0" />

		<!-- Base percent chance per millisol that a person at high fatigue will
			collapse. -->
		<!-- See medical complaint: "High Fatigue Collapse" in medical.xml. -->
		<!-- Default: 10 [in percentage] -->
		<high-fatigue-collapse-chance value="10.0" />
	</person-attributes>

	<!-- Myers-Briggs Type Indicator: http://www.wikipedia.org/wiki/MBTI -->
	<!-- TODO: Find statistics appropriate for Martian settlers, perhaps from
		personality studies of scientists, -->
	<!-- engineers or computer programmers. -->
	<!-- The Proposed average percentages of the 16 MBTI among settlers are
		as follows -->
	<personality-types>
		<!-- Note: The total percentage for all personality types must equal 100%. -->
		<mbti type="ISTP" percentage="3.0" />
		<mbti type="ISTJ" percentage="19.0" />
		<mbti type="ISFP" percentage="2.0" />
		<mbti type="ISFJ" percentage="8.0" />
		<mbti type="INTP" percentage="6.0" />
		<mbti type="INTJ" percentage="7.0" />
		<mbti type="INFP" percentage="6.0" />
		<mbti type="INFJ" percentage="5.0" />
		<mbti type="ESTP" percentage="2.0" />
		<mbti type="ESTJ" percentage="13.0" />
		<mbti type="ESFP" percentage="2.0" />
		<mbti type="ESFJ" percentage="8.0" />
		<mbti type="ENTP" percentage="4.0" />
		<mbti type="ENTJ" percentage="3.0" />
		<mbti type="ENFP" percentage="7.0" />
		<mbti type="ENFJ" percentage="5.0" />
	</personality-types>

	<training-list>
		<training name="MARS_V_GOBI">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="3"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="2"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="4"/>
			<benefit role="MISSION_SPECIALIST" modifier="4"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="5"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="4"/>
			<benefit role="SAFETY_SPECIALIST" modifier="3"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="6"/>
		</training>
		<training name="NASA_CHAPEA">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="5"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="2"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="2"/>
			<benefit role="MISSION_SPECIALIST" modifier="5"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="6"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="4"/>
			<benefit role="SAFETY_SPECIALIST" modifier="2"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="7"/>
		</training>
		<training name="UNDERGROUND_CAVES_EXPLORATION">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="5"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="3"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="5"/>
			<benefit role="MISSION_SPECIALIST" modifier="4"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="8"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="4"/>
			<benefit role="SAFETY_SPECIALIST" modifier="7"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="6"/>
		</training>
		<training name="BIOETHICAL">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="8"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="1"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="7"/>
			<benefit role="MISSION_SPECIALIST" modifier="2"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="2"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="4"/>
			<benefit role="SAFETY_SPECIALIST" modifier="5"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="6"/>
		</training>
		<training name="EXTREME_ENV_OPS">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="6"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="2"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="6"/>
			<benefit role="MISSION_SPECIALIST" modifier="6"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="4"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="5"/>
			<benefit role="SAFETY_SPECIALIST" modifier="3"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="8"/>
		</training> 
		<training name="NASA_DESERT_RATS">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="2"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="3"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="6"/>
			<benefit role="MISSION_SPECIALIST" modifier="6"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="8"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="5"/>
			<benefit role="SAFETY_SPECIALIST" modifier="3"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="8"/>
		</training>
		<training name="SURVIVAL_TRAINING">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="6"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="1"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="2"/>
			<benefit role="MISSION_SPECIALIST" modifier="4"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="8"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="7"/>
			<benefit role="SAFETY_SPECIALIST" modifier="5"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="3"/>
		</training>
		<training name="SCUBA_DIVING_MASTER">
			<benefit role="COMPUTING_SPECIALIST" modifier="1"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="2"/>
			<benefit role="MISSION_SPECIALIST" modifier="5"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="8"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="6"/>
			<benefit role="SAFETY_SPECIALIST" modifier="6"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="2"/>
		</training>
		<training name="FLIGHT_SAFETY">
			<benefit role="COMPUTING_SPECIALIST" modifier="4"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="6"/>
			<benefit role="MISSION_SPECIALIST" modifier="4"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="4"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="2"/>
			<benefit role="SAFETY_SPECIALIST" modifier="8"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="5"/>
		</training>	
		<training name="SEARCH_AND_RESCUE">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="1"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="3"/>
			<benefit role="MISSION_SPECIALIST" modifier="8"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="8"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="4"/>
			<benefit role="SAFETY_SPECIALIST" modifier="7"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="1"/>
		</training>
		<training name="MOUNTAINEERING_MASTER">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="1"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="1"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="2"/>
			<benefit role="MISSION_SPECIALIST" modifier="7"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="9"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="4"/>
			<benefit role="SAFETY_SPECIALIST" modifier="8"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="2"/>
		</training>
		<training name="AIRBORNE_AND_RANGER_SCHOOL">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="4"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="2"/>
			<benefit role="MISSION_SPECIALIST" modifier="9"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="6"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="8"/>
			<benefit role="SAFETY_SPECIALIST" modifier="4"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="1"/>
		</training>
		<training name="HAUGHTON_MARS_GEOLOGICAL">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="6"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="5"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="6"/>
			<benefit role="MISSION_SPECIALIST" modifier="6"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="4"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="5"/>
			<benefit role="SAFETY_SPECIALIST" modifier="3"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="8"/>
		</training>
		<training name="HALO_JUMPMASTER">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="1"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="3"/>
			<benefit role="MISSION_SPECIALIST" modifier="4"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="9"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="8"/>
			<benefit role="SAFETY_SPECIALIST" modifier="2"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="2"/>
		</training>
		<training name="MISHAP_INVESTIGATION">
			<benefit role="COMPUTING_SPECIALIST" modifier="3"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="7"/>
			<benefit role="MISSION_SPECIALIST" modifier="5"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="8"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="2"/>
			<benefit role="SAFETY_SPECIALIST" modifier="9"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="5"/>
		</training>
		<training name="MARS_500_C">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="6"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="4"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="4"/>
			<benefit role="MISSION_SPECIALIST" modifier="6"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="4"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="5"/>
			<benefit role="SAFETY_SPECIALIST" modifier="2"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="7"/>
		</training>
		<training name="MARS_ANALOG_ENVIRONMENT">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="7"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="4"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="5"/>
			<benefit role="MISSION_SPECIALIST" modifier="6"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="4"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="5"/>
			<benefit role="SAFETY_SPECIALIST" modifier="2"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="8"/>
		</training>
		<training name="UNDERSEA_MISSION">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="3"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="3"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="6"/>
			<benefit role="MISSION_SPECIALIST" modifier="6"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="4"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="5"/>
			<benefit role="SAFETY_SPECIALIST" modifier="3"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="8"/>
		</training>
		<training name="MILITARY_DEPLOYMENT">
			<benefit role="COMPUTING_SPECIALIST" modifier="2"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="2"/>
			<benefit role="MISSION_SPECIALIST" modifier="9"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="8"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="5"/>
			<benefit role="SAFETY_SPECIALIST" modifier="5"/>
		</training>
		<training name="AVIATION_CERTIFICATION">
			<benefit role="COMPUTING_SPECIALIST" modifier="5"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="4"/>
			<benefit role="MISSION_SPECIALIST" modifier="3"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="4"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="3"/>
			<benefit role="SAFETY_SPECIALIST" modifier="9"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="2"/>
		</training>
		<training name="ANTARCTICA_EDEN_ISS">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="8"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="5"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="7"/>
			<benefit role="MISSION_SPECIALIST" modifier="4"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="4"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="6"/>
			<benefit role="SAFETY_SPECIALIST" modifier="2"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="9"/>
		</training> 		
		<training name="MARS_TWO_FINAL_100">
			<benefit role="AGRICULTURE_SPECIALIST" modifier="5"/>
			<benefit role="COMPUTING_SPECIALIST" modifier="5"/>
			<benefit role="ENGINEERING_SPECIALIST" modifier="4"/>
			<benefit role="MISSION_SPECIALIST" modifier="6"/>
			<benefit role="LOGISTIC_SPECIALIST" modifier="4"/>
			<benefit role="RESOURCE_SPECIALIST" modifier="5"/>
			<benefit role="SAFETY_SPECIALIST" modifier="2"/>
			<benefit role="SCIENCE_SPECIALIST" modifier="3"/>
		</training>
	</training-list>	

	<country-list>
		<country name="Brazil">
			<first-name-list>
				<!-- Brazil : will replace with Brazilian names -->
				<first-name value="Paulo" gender="male" />
				<first-name value="Eduardo" gender="male" />		
				<first-name value="Marcos" gender="male" />
				
				<!--http://iheartbrazil.com/brazilian-boy-names/ -->
				<first-name value="Jose" gender="male" />
				<first-name value="Joao" gender="male" />
				<first-name value="Antonio" gender="male" />
				<first-name value="Francisco" gender="male" />
				<first-name value="Carlos" gender="male" />
				<first-name value="Pedro" gender="male" />
				<first-name value="Lucas" gender="male" />
				<first-name value="Luiz" gender="male" />
						
				<first-name value="Adriano" gender="male" />
				<first-name value="Afonso" gender="male" />
				<first-name value="Alexandre" gender="male" />
				<first-name value="Andre" gender="male" />
				<first-name value="Arthur" gender="male" />
				<first-name value="Augusto" gender="male" />
				
				<first-name value="Benicio" gender="male" />
				<first-name value="Benjamim" gender="male" />
				<first-name value="Bento" gender="male" />
				<first-name value="Breno" gender="male" />
				<first-name value="Bernardo" gender="male" />
				<first-name value="Bruno" gender="male" />
				
				<first-name value="Caio" gender="male" />
				<first-name value="Carlos" gender="male" />
				<first-name value="Caua" gender="male" />
				<first-name value="Cesar" gender="male" />
				<first-name value="Cleiton" gender="male" />
				<first-name value="Claudio" gender="male" />
				<first-name value="Cristiano" gender="male" />

				<first-name value="Damiao" gender="male" />
				<first-name value="Danilo" gender="male" />
				<first-name value="Davi" gender="male" />
				<first-name value="Diego" gender="male" />
				<first-name value="Domingos" gender="male" />
				
				
				<!--http://iheartbrazil.com/brazilian-girl-names/ -->
				<first-name value="Michele" gender="female" />
				
				<first-name value="Bruna" gender="female" />
				
				<first-name value="Maria" gender="female" />
				<first-name value="Ana" gender="female" />
				<first-name value="Francisca" gender="female" />
				<first-name value="Antonia" gender="female" />
				<first-name value="Adriana" gender="female" />
				<first-name value="Juliana" gender="female" />
				<first-name value="Marcia" gender="female" />
				<first-name value="Fernanda" gender="female" />
				<first-name value="Patricia" gender="female" />
				<first-name value="Aline" gender="female" />
				
				
				<first-name value="Adriene" gender="female" />
				<first-name value="Agata" gender="female" />
				<first-name value="Alessandra" gender="female" />

				<first-name value="Amelia" gender="female" />
				<first-name value="Anita" gender="female" />
				<first-name value="Aline" gender="female" />
				<first-name value="Alzira" gender="female" />
				<first-name value="Ana" gender="female" />

				<first-name value="Analu" gender="female" />
				<first-name value="Andreia" gender="female" />
				<first-name value="Aparecida" gender="female" />
				<first-name value="Aurea" gender="female" />
				
				
				<first-name value="Beatriz" gender="female" />

				<first-name value="Belinda" gender="female" />
				<first-name value="Bethania" gender="female" />
				<first-name value="Bibiana" gender="female" />
				<first-name value="Bruna" gender="female" />
				
				<first-name value="Camila" gender="female" />

				<first-name value="Carina" gender="female" />
				<first-name value="Carla" gender="female" />
				<first-name value="Carolina" gender="female" />
				<first-name value="Cassia" gender="female" />
				<first-name value="Catarina" gender="female" />

				<first-name value="Celia" gender="female" />
				<first-name value="Cintia" gender="female" />
				<first-name value="Conceicao" gender="female" />
				<first-name value="Claudia" gender="female" />
				<first-name value="Cristiana" gender="female" />

			</first-name-list>
			<last-name-list>
				<!--http://iheartbrazil.com/brazilian-last-names/ -->
				
				<last-name value="Pontes" />
				<last-name value="Melo" />
				<last-name value="Vasconcellos" />
				
				<last-name value="Silva" />
				<last-name value="Santos" />
				<last-name value="Olveira" />
				<last-name value="Souza" />
				<last-name value="Rodrigues" />
				<last-name value="Ferreira" />
				<last-name value="Alves" />

				<last-name value="Anjos" />
				<last-name value="Assuncao" />
				<last-name value="Batista" />
				<last-name value="Santiago" />
				<last-name value="Trindade" />

				<last-name value="Graca" />
				<last-name value="Pereira" />
				<last-name value="Lima" />
				<last-name value="carvalho" />
				<last-name value="Gomes" />

				<last-name value="Costa" />
				<last-name value="Ribeiro" />
				<last-name value="Martins" />
				<last-name value="Almeida" />
				<last-name value="Lopes" />

				<last-name value="Soares" />
				<last-name value="Fernandes" />
				<last-name value="Vieira" />
				<last-name value="Barbosa" />
				<last-name value="Rocha" />

				<last-name value="Dias" />
				<last-name value="Nascimento" />
				<last-name value="Andrade" />

				<last-name value="Moreira" />
				<last-name value="Nunes" />
				<last-name value="Marques" />
				<last-name value="Machado" />
				<last-name value="Mendes" />

				<last-name value="Freitas" />
				<last-name value="Cardoso" />
				<last-name value="Ramos" />
				<last-name value="Goncalves" />
				<last-name value="Santana" />

				<last-name value="Teixeira" />
				<last-name value="Araujo" />
				<last-name value="Conceicao" />
				<last-name value="Bezerra" />
				<last-name value="Campos" />

				<last-name value="Reis" />
				<last-name value="Moraes" />
				<last-name value="Borges" />
				<last-name value="Castro" />
				<last-name value="Monteiro" />

				<last-name value="Moura" />
				<last-name value="Miranda" />
				<last-name value="Garcia" />
				<last-name value="Duarte" />
				<last-name value="Medeiros" />				
			</last-name-list>
		</country>
	
		<country name="China">
			<first-name-list>
				<!-- Derived from https://en.wiki2.org/wiki/List_of_Chinese_astronauts
					http://www.20000-names.com/male_chinese_names.htm -->
				<first-name value="Boming" gender="male" />
				<first-name value="Chongfu" gender="male" />
				<first-name value="Dazhe" gender="male" />
				<first-name value="Donghai" gender="male" />

				<first-name value="Enlai" gender="male" />
				<first-name value="Haipeng" gender="male" />
				<first-name value="Haisheng" gender="male" />
				<first-name value="Hongliang" gender="male" />
				<first-name value="Junlong" gender="male" />

				<first-name value="Liwei" gender="male" />
				<first-name value="Ming" gender="male" />
				<first-name value="Qinghua" gender="male" />
				<first-name value="Qiu" gender="male" />