<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE settlement-configuration [
	<!ELEMENT settlement-configuration (mission-control, life-support-requirements, settlement-template-list,
	initial-settlement-list, new-arriving-settlement-list, settlement-name-list)>
	
	<!ELEMENT mission-control (rover-life-support-range-error-margin, rover-fuel-range-error-margin)>
	<!ELEMENT rover-life-support-range-error-margin EMPTY>
	<!ATTLIST rover-life-support-range-error-margin value CDATA #REQUIRED>
	<!ELEMENT rover-fuel-range-error-margin EMPTY>
	<!ATTLIST rover-fuel-range-error-margin value CDATA #REQUIRED>
	
	<!ELEMENT life-support-requirements (total-pressure, partial-pressure-of-oxygen, 
	partial-pressure-of-nitrogen, partial-pressure-of-carbon-dioxide, temperature,
	relative-humidity, ventilation)>
	<!ELEMENT total-pressure EMPTY>
	<!ATTLIST total-pressure low CDATA #REQUIRED>
	<!ATTLIST total-pressure high CDATA #REQUIRED>
	<!ELEMENT partial-pressure-of-oxygen EMPTY>
	<!ATTLIST partial-pressure-of-oxygen low CDATA #REQUIRED>
	<!ATTLIST partial-pressure-of-oxygen high CDATA #REQUIRED>
	<!ELEMENT partial-pressure-of-nitrogen EMPTY>
	<!ATTLIST partial-pressure-of-nitrogen low CDATA #REQUIRED>
	<!ATTLIST partial-pressure-of-nitrogen high CDATA #REQUIRED>
	<!ELEMENT partial-pressure-of-carbon-dioxide EMPTY>
	<!ATTLIST partial-pressure-of-carbon-dioxide low CDATA #REQUIRED>
	<!ATTLIST partial-pressure-of-carbon-dioxide high CDATA #REQUIRED>
	<!ELEMENT temperature EMPTY>
	<!ATTLIST temperature low CDATA #REQUIRED>
	<!ATTLIST temperature high CDATA #REQUIRED>
	<!ELEMENT relative-humidity EMPTY>
	<!ATTLIST relative-humidity low CDATA #REQUIRED>
	<!ATTLIST relative-humidity high CDATA #REQUIRED>
	<!ELEMENT ventilation EMPTY>
	<!ATTLIST ventilation low CDATA #REQUIRED>
	<!ATTLIST ventilation high CDATA #REQUIRED>
	
	<!ELEMENT settlement-template-list (template*)>
	<!ELEMENT template (building*, vehicle*, equipment*, resource*, part*, part-package*, resupply?)>
	<!ATTLIST template name CDATA #REQUIRED>
	<!ATTLIST template default-population CDATA #REQUIRED>
	<!ATTLIST template number-of-robots CDATA #REQUIRED>
	<!ATTLIST template sponsor CDATA #REQUIRED>
	<!ELEMENT building (connection-list?)>
	<!ATTLIST building id CDATA #REQUIRED>
	<!ATTLIST building type CDATA #REQUIRED>
	<!ATTLIST building width CDATA #IMPLIED>
	<!ATTLIST building length CDATA #IMPLIED>
	<!ATTLIST building x-location CDATA #REQUIRED>
	<!ATTLIST building y-location CDATA #REQUIRED>
	<!ATTLIST building facing CDATA #REQUIRED>
	<!ELEMENT connection-list (connection*)>
	<!ELEMENT connection EMPTY>
	<!ATTLIST connection id CDATA #REQUIRED>
	<!ATTLIST connection x-location CDATA #REQUIRED>
	<!ATTLIST connection y-location CDATA #REQUIRED>
	<!ELEMENT vehicle EMPTY>
	<!ATTLIST vehicle type CDATA #REQUIRED>
	<!ATTLIST vehicle number CDATA #REQUIRED>
	<!ELEMENT equipment EMPTY>
	<!ATTLIST equipment type CDATA #REQUIRED>
	<!ATTLIST equipment number CDATA #REQUIRED>
	<!ELEMENT resource EMPTY>
	<!ATTLIST resource type CDATA #REQUIRED>
	<!ATTLIST resource amount CDATA #REQUIRED>
	<!ELEMENT part EMPTY>
	<!ATTLIST part type CDATA #REQUIRED>
	<!ATTLIST part number CDATA #REQUIRED>
	<!ELEMENT part-package EMPTY>
	<!ATTLIST part-package name CDATA #REQUIRED>
	<!ATTLIST part-package number CDATA #REQUIRED>
	<!ELEMENT resupply (resupply-mission*)>
	<!ELEMENT resupply-mission EMPTY>
	<!ATTLIST resupply-mission name CDATA #REQUIRED>
	<!ATTLIST resupply-mission arrival-time CDATA #REQUIRED>
	
	<!ELEMENT initial-settlement-list (settlement*)>
	<!ELEMENT settlement (location, population, number-of-robots, sponsor)>
	<!ATTLIST settlement name CDATA #REQUIRED>
	<!ATTLIST settlement template CDATA #REQUIRED>
	
	<!ELEMENT new-arriving-settlement-list (arriving-settlement*)>
	<!ELEMENT arriving-settlement (location, population, number-of-robots, sponsor)>
	<!ATTLIST arriving-settlement name CDATA #REQUIRED>
	<!ATTLIST arriving-settlement template CDATA #REQUIRED>
	<!ATTLIST arriving-settlement arrival-time CDATA #REQUIRED>
	<!ELEMENT location EMPTY>
	<!ATTLIST location longitude CDATA #REQUIRED>
	<!ATTLIST location latitude CDATA #REQUIRED>
	<!ELEMENT population EMPTY>
	<!ATTLIST population number CDATA #REQUIRED>
	<!ELEMENT number-of-robots EMPTY>
	<!ATTLIST number-of-robots number CDATA #REQUIRED>
	<!ELEMENT sponsor EMPTY>
	<!ATTLIST sponsor name CDATA #REQUIRED>
	
	<!ELEMENT settlement-name-list (settlement-name*)>
	<!ELEMENT settlement-name EMPTY>
	<!ATTLIST settlement-name sponsor CDATA #REQUIRED>
	<!ATTLIST settlement-name value CDATA #REQUIRED>
]>

<settlement-configuration>

	<!-- Typical mission control parameters for a settlement  -->
	<mission-control>

		<!-- This vehicle range error margin imposed on the life support/consumable. -->
		<!-- This value will multiply with the amount of each resource needed for the mission -->
		<!-- The higher the value, the more amount of this resource a rover will bring -->
		<!-- default value : 1.5  Valid from 1.0 to 3.0 -->
		<rover-life-support-range-error-margin value="1.5" />

		<!-- This vehicle range error margin imposed on the fuel of the vehicle. -->
		<!-- This value will multiply with the amount of fuel needed for the mission -->
		<!-- The higher the value, the more fuel a rover will bring -->
		<!-- default value : 1.4  Valid from 1.0 to 3.0 -->
		<rover-fuel-range-error-margin value="1.4" />

	</mission-control>

	<!-- (NOT IMPLEMENTED YET) Typical atmospheric requirements for a closed-loop habitat  
	     see http://www2.le.ac.uk/offices/safety-services/documents/pdfs/air-monitoring-guide.pdf 
	     
	Note : a 340 mb or 34kPa indoor atmosphere is currently being implemented 
	     
    -->
	<life-support-requirements>

		<!-- recommended range of total air pressure in kPa -->				
		<total-pressure low="32" high="36" />
		<!-- recommended range of partial pressure for O2 in kPa -->		
		<partial-pressure-of-oxygen low="18" high="22" />
		<!-- recommended range of partial pressure for NO2 in kPa -->				
		<partial-pressure-of-nitrogen low="10" high="14"/>
		<!-- recommended range of partial pressure for CO2 in kPa -->		
		<partial-pressure-of-carbon-dioxide low="0.03" high="0.07" />
		<!-- recommended range of temperatures [in degree celsius]-->
		<temperature low="18" high="26"/>
		<!-- humidity in %-->
		<relative-humidity low="30" high="70"/>
		<!-- ventilation in m/s-->
		<ventilation low="0.076" high="0.203"/>

	</life-support-requirements>

	<!-- List of templates for settlements -->
	<settlement-template-list>

		<!-- Settlement template for the Zubrin Mars Direct mission plan. -->
		<!-- See http://www.marssociety.org/home/about/mars-direct for more info. -->
		<!-- default-population: the default population capacity for the template. -->
		<!-- number-of-robots: the default number of robots for the template. -->
		<!-- sponsor: the name of the sponsoring organization for the template. -->
		<template name="Mars Direct Base (Phase 1)" default-population="4" number-of-robots="2" sponsor="Mars Society (MS)">

			<!-- Lander habitat building is the main habitation in the Mars Direct mission plan. -->
			<building id="0" type="Lander Hab" x-location="0.0" y-location="0.0" facing="0.0">
				<!-- List of all connections to other buildings (optional). -->
				<connection-list>
					<!-- Connection to another building.  "id" is other building's ID. -->
					<!-- X & Y locations are relative to this building, not in the settlement locale. -->
					<connection id="1" x-location="4.5" y-location="0.0" />
					<connection id="2" x-location="-4.5" y-location="0.0" />
				</connection-list>
			</building>

			<!-- EVA Airlock is attached to the lander hab -->
			<building id="1" type="EVA Airlock" x-location="7.5" y-location="0.0" facing="0.0">
				<connection-list>
					<connection id="0" x-location="-3.0" y-location="0.0" />
				</connection-list>
			</building>

			<!-- Hallway connecting lander hab and inflatable greenhouse. -->
			<!-- Note: Aa hallway has fixed width but variable length. Therefore, the length argument must be provided below. -->
			<building id="2" type="Hallway" length="3.0" x-location="-6.0" y-location="0.0" facing="270.0">
				<connection-list>
					<connection id="0" x-location="0.0" y-location="1.5" />
					<connection id="3" x-location="0.0" y-location="-1.5" />
				</connection-list>
			</building>
			
			<!-- Inflatable greenhouse can be used to grow crops. -->
			<building id="3" type="Inflatable Greenhouse" x-location="-12.0" y-location="0.0" facing="270.0">
				<connection-list>
					<connection id="2" x-location="0.0" y-location="4.5" />
				</connection-list>
			</building>

			<!-- Small nuclear reactor power generator. -->
			<building id="4" type="MD1 Nuclear Reactor" x-location="40.0" y-location="-60.0" facing="0.0" />
			<building id="5" type="MD1 Nuclear Reactor" x-location="40.0" y-location="-80.0" facing="0.0" />
			<building id="6" type="MD1 Nuclear Reactor" x-location="60.0" y-location="-60.0" facing="0.0" />
			
			<!-- Earth Return Vehicle base building with Sabatier reactor for converting
			     hydrogen and carbon dioxide into methane, water and oxygen.
			     The starting ERV base has a full load of hydrogen and has not reacted yet. -->
			<building id="7" type="Starting ERV Base" x-location="40.0" y-location="15.0" facing="135.0" />

			<!-- Earth Return Vehicle base building with Sabatier reactor for converting
			     hydrogen and carbon dioxide into methane, water and oxygen.  -->
			<building id="8" type="ERV Base" x-location="40.0" y-location="-15.0" facing="45.0" />

			<building id="9" type="Large Sabatier Processor" x-location="0.0" y-location="-40.0" facing="90.0" />

			<building id="10" type="Large Sabatier Processor" x-location="0.0" y-location="-65.0" facing="90.0" />		
			<!-- A rover for collecting rock samples from remote sites
			     and ice prospecting. -->
			<vehicle type="Explorer Rover" number="2" />
			<vehicle type="Light Utility Vehicle" number="1" />

			<!-- Equipment -->
			<equipment type="EVA Suit" number="8" />
			<equipment type="Gas Canister" number="40" />
			<equipment type="Barrel" number="40" />
			<equipment type="Bag" number="40" />
			<equipment type="Large Bag" number="10" />
			<equipment type="Specimen Box" number="50" />

			<!-- Resources -->
			<!-- type: the type of resource (see resources.txt) -->
			<!-- amount: the amount of the resource (kg) -->
			
			<!-- Mars Direct Mission Plan : 
			
			(1). ERV - 
		 	(a). Payload imported from Earth -
			 	 Consumables : 3400 kg
			 	 Hydrogen feedstock : 6300 kg
			(b). Produced on Mars :
				 water : 18900 kg
				 Oxygen : 16080 kg
				 Methane : 8400 kg

			(2). Hab -
			(a). Payload imported from Earth -
			 	 Consumables : 7000 kg				 
			 -->
		
			<!-- Crop -->
			<!-- No starting crops for this template -->

			<!-- Part packages (see part_packages.xml) -->
			<!-- name: the part package name. -->
			<!-- number: the number of packages. -->
			<part-package name="package 1" number="1" />

			<!-- The resupply missions from Earth scheduled for this type of settlement. -->
			<resupply>
				<!-- Resupply mission from Earth. -->
			    <!-- name: the resupply mission's name  -->
				<!-- arrival-time: arrival time (in Sols) since the settlement is founded.  -->
				<!-- (668 Sols = 1 Martian orbit) -->
				<resupply-mission name="Mars Direct Base Resupply 1" arrival-time="668.0" />
				<resupply-mission name="Mars Direct Base Resupply 2" arrival-time="1336.0" />
				<resupply-mission name="Mars Direct Base Resupply 3" arrival-time="2004.0" />
			</resupply>
		</template>

		<template name="Mars Direct Base (Phase 1A)" default-population="4" number-of-robots="2" sponsor="National Aeronautics and Space Administration (NASA)">

			<building id="0" type="Lander Hab" x-location="0.0" y-location="0.0" facing="0.0">
				<connection-list>
					<connection id="1" x-location="4.5" y-location="0.0" />
					<connection id="2" x-location="-4.5" y-location="0.0" />					
				</connection-list>
			</building>

			<!-- EVA Airlock is attached to the lander hab -->
			<building id="1" type="EVA Airlock" x-location="7.5" y-location="0.0" facing="0.0">
				<connection-list>
					<connection id="0" x-location="-3.0" y-location="0.0" />
				</connection-list>
			</building>
			
			<building id="2" type="Hallway" length="3.0" x-location="-6.0" y-location="0.0" facing="270.0">
				<connection-list>
					<connection id="0" x-location="0.0" y-location="1.5" />
					<connection id="3" x-location="0.0" y-location="-1.5" />
				</connection-list>
			</building>
			
			<building id="3" type="Laboratory" x-location="-12.0" y-location="0.0" facing="270.0">
				<connection-list>
					<connection id="2" x-location="0.0" y-location="4.5" />
					<connection id="4" x-location="0.0" y-location="-4.5" />
				</connection-list>
			</building>
			
			<building id="4" type="Hallway" length="3.0" x-location="-18.0" y-location="0.0" facing="270.0">
				<connection-list>
					<connection id="3" x-location="0.0" y-location="1.5" />
					<connection id="5" x-location="0.0" y-location="-1.5" />
				</connection-list>
			</building>
			
			<building id="5" type="Inflatable Greenhouse" x-location="-24.0" y-location="0.0" facing="270.0">
				<connection-list>
					<connection id="4" x-location="0.0" y-location="4.5" />
				</connection-list>
			</building>

			<building id="6" type="MD1 Nuclear Reactor" x-location="40.0" y-location="-60.0" facing="0.0" />
			<building id="7" type="MD1 Nuclear Reactor" x-location="40.0" y-location="-80.0" facing="0.0" />
			<building id="8" type="MD1 Nuclear Reactor" x-location="60.0" y-location="-60.0" facing="0.0" />

			<building id="9" type="Starting ERV Base" x-location="40.0" y-location="15.0" facing="135.0" />

			<building id="10" type="ERV Base" x-location="40.0" y-location="-15.0" facing="45.0" />

			<building id="11" type="Large Sabatier Processor" x-location="0.0" y-location="-40.0" facing="90.0" />

			<building id="12" type="Large Sabatier Processor" x-location="0.0" y-location="-65.0" facing="90.0" />		

			<vehicle type="Explorer Rover" number="2" />
			<vehicle type="Light Utility Vehicle" number="1" />

			<equipment type="EVA Suit" number="8" />
			<equipment type="Gas Canister" number="40" />
			<equipment type="Barrel" number="40" />
			<equipment type="Bag" number="40" />
			<equipment type="Large Bag" number="10" />
			<equipment type="Specimen Box" number="50" />

			<part-package name="package 1" number="1" />

			<resupply>
				<resupply-mission name="Mars Direct Base Resupply 1" arrival-time="668.0" />
				<resupply-mission name="Mars Direct Base Resupply 2" arrival-time="1336.0" />
				<resupply-mission name="Mars Direct Base Resupply 3" arrival-time="2004.0" />
			</resupply>
		</template>

		<template name="Mars Direct Base (Phase 1B)" default-population="4" number-of-robots="2" sponsor="China National Space Administration (CNSA)">

			<building id="0" type="Lander Hab" x-location="0.0" y-location="0.0" facing="0.0">
				<connection-list>
					<connection id="1" x-location="4.5" y-location="0.0" />
					<connection id="2" x-location="-4.5" y-location="0.0" />					
				</connection-list>
			</building>

			<!-- EVA Airlock is attached to the lander hab -->
			<building id="1" type="EVA Airlock" x-location="7.5" y-location="0.0" facing="0.0">
				<connection-list>
					<connection id="0" x-location="-3.0" y-location="0.0" />
				</connection-list>
			</building>
			
			<building id="2" type="Hallway" length="3.0" x-location="-6.0" y-location="0.0" facing="270.0">
				<connection-list>
					<connection id="0" x-location="0.0" y-location="1.5" />
					<connection id="3" x-location="0.0" y-location="-1.5" />
				</connection-list>
			</building>
			
			<building id="3" type="Workshop" x-location="-12.0" y-location="0.0" facing="270.0">
				<connection-list>
					<connection id="2" x-location="0.0" y-location="4.5" />
					<connection id="4" x-location="0.0" y-location="-4.5" />
				</connection-list>
			</building>
			
			<building id="4" type="Hallway" length="3.0" x-location="-18.0" y-location="0.0" facing="270.0">
				<connection-list>
					<connection id="3" x-location="0.0" y-location="1.5" />
					<connection id="5" x-location="0.0" y-location="-1.5" />
				</connection-list>
			</building>
			
			<building id="5" type="Inflatable Greenhouse" x-location="-24.0" y-location="0.0" facing="270.0">
				<connection-list>
					<connection id="4" x-location="0.0" y-location="4.5" />
				</connection-list>
			</building>

			<building id="6" type="MD1 Nuclear Reactor" x-location="40.0" y-location="-60.0" facing="0.0" />
			<building id="7" type="MD1 Nuclear Reactor" x-location="40.0" y-location="-80.0" facing="0.0" />
			<building id="8" type="MD1 Nuclear Reactor" x-location="60.0" y-location="-60.0" facing="0.0" />

			<building id="9" type="Starting ERV Base" x-location="40.0" y-location="15.0" facing="135.0" />

			<building id="10" type="ERV Base" x-location="40.0" y-location="-15.0" facing="45.0" />

			<building id="11" type="Large Sabatier Processor" x-location="0.0" y-location="-40.0" facing="90.0" />

			<building id="12" type="Large Sabatier Processor" x-location="0.0" y-location="-65.0" facing="90.0" />		

			<vehicle type="Explorer Rover" number="2" />
			<vehicle type="Light Utility Vehicle" number="1" />

			<equipment type="EVA Suit" number="8" />
			<equipment type="Gas Canister" number="40" />
			<equipment type="Barrel" number="40" />
			<equipment type="Bag" number="40" />
			<equipment type="Large Bag" number="10" />
			<equipment type="Specimen Box" number="50" />

			<part-package name="package 1" number="1" />

			<resupply>
				<resupply-mission name="Mars Direct Base Resupply 1" arrival-time="668.0" />
				<resupply-mission name="Mars Direct Base Resupply 2" arrival-time="1336.0" />
				<resupply-mission name="Mars Direct Base Resupply 3" arrival-time="2004.0" />
			</resupply>
		</template>

		<template name="Mars Direct Base (Phase 1C)" default-population="4" number-of-robots="2" sponsor="Indian Space Research Organisation (ISRO)">

			<building id="0" type="Lander Hab" x-location="0.0" y-location="0.0" facing="0.0">
				<connection-list>
					<connection id="1" x-location="4.5" y-location="0.0" />
					<connection id="2" x-location="-4.5" y-location="0.0" />					
				</connection-list>
			</building>

			<!-- EVA Airlock is attached to the lander hab -->
			<building id="1" type="EVA Airlock" x-location="7.5" y-location="0.0" facing="0.0">
				<connection-list>
					<connection id="0" x-location="-3.0" y-location="0.0" />
				</connection-list>
			</building>
			
			<building id="2" type="Hallway" length="3.0" x-location="-6.0" y-location="0.0" facing="270.0">
				<connection-list>
					<connection id="0" x-location="0.0" y-location="1.5" />
					<connection id="3" x-location="0.0" y-location="-1.5" />
				</connection-list>
			</building>
			
			<building id="3" type="Lounge" x-location="-12.0" y-location="0.0" facing="270.0">
				<connection-list>
					<connection id="2" x-location="0.0" y-location="4.5" />
					<connection id="4" x-location="0.0" y-location="-4.5" />
				</connection-list>
			</building>
			
			<building id="4" type="Hallway" length="3.0" x-location="-18.0" y-location="0.0" facing="270.0">
				<connection-list>
					<connection id="3" x-location="0.0" y-location="1.5" />
					<connection id="5" x-location="0.0" y-location="-1.5" />
				</connection-list>
			</building>
			
			<building id="5" type="Inflatable Greenhouse" x-location="-24.0" y-location="0.0" facing="270.0">
				<connection-list>
					<connection id="4" x-location="0.0" y-location="4.5" />
				</connection-list>
			</building>

			<building id="6" type="MD1 Nuclear Reactor" x-location="40.0" y-location="-60.0" facing="0.0" />
			<building id="7" type="MD1 Nuclear Reactor" x-location="40.0" y-location="-80.0" facing="0.0" />
			<building id="8" type="MD1 Nuclear Reactor" x-location="60.0" y-location="-60.0" facing="0.0" />

			<building id="9" type="Starting ERV Base" x-location="40.0" y-location="15.0" facing="135.0" />

			<building id="10" type="ERV Base" x-location="40.0" y-location="-15.0" facing="45.0" />

			<building id="11" type="Large Sabatier Processor" x-location="0.0" y-location="-40.0" facing="90.0" />

			<building id="12" type="Large Sabatier Processor" x-location="0.0" y-location="-65.0" facing="90.0" />		

			<vehicle type="Explorer Rover" number="2" />
			<vehicle type="Light Utility Vehicle" number="1" />

			<equipment type="EVA Suit" number="8" />
			<equipment type="Gas Canister" number="40" />
			<equipment type="Barrel" number="40" />
			<equipment type="Bag" number="40" />
			<equipment type="Large Bag" number="10" />
			<equipment type="Specimen Box" number="50" />

			<part-package name="package 1" number="1" />

			<resupply>
				<resupply-mission name="Mars Direct Base Resupply 1" arrival-time="668.0" />
				<resupply-mission name="Mars Direct Base Resupply 2" arrival-time="1336.0" />
				<resupply-mission name="Mars Direct Base Resupply 3" arrival-time="2004.0" />
			</resupply>
		</template>

		<template name="Mars Direct Base (Phase 1D)" default-population="4" number-of-robots="2" sponsor="Roscosmos (RKA)">

			<building id="0" type="Lander Hab" x-location="0.0" y-location="0.0" facing="0.0">
				<connection-list>
					<connection id="1" x-location="4.5" y-location="0.0" />
					<connection id="2" x-location="-4.5" y-location="0.0" />					
				</connection-list>
			</building>

			<!-- EVA Airlock is attached to the lander hab -->
			<building id="1" type="EVA Airlock" x-location="7.5" y-location="0.0" facing="0.0">
				<connection-list>
					<connection id="0" x-location="-3.0" y-location="0.0" />
				</connection-list>
			</building>
			
			<building id="2" type="Hallway" length="3.0" x-location="-6.0" y-location="0.0" facing="270.0">
				<connection-list>
					<connection id="0" x-location="0.0" y-location="1.5" />
					<connection id="3" x-location="0.0" y-location="-1.5" />
				</connection-list>
			</building>
			
			<building id="3" type="Infirmary" x-location="-12.0" y-location="0.0" facing="270.0">
				<connection-list>
					<connection id="2" x-location="0.0" y-location="4.5" />
					<connection id="4" x-location="0.0" y-location="-4.5" />
				</connection-list>
			</building>
			
			<building id="4" type="Hallway" length="3.0" x-location="-18.0" y-location="0.0" facing="270.0">
				<connection-list>
					<connection id="3" x-location="0.0" y-location="1.5" />
					<connection id="5" x-location="0.0" y-location="-1.5" />
				</connection-list>
			</building>
			
			<building id="5" type="Inflatable Greenhouse" x-location="-24.0" y-location="0.0" facing="270.0">
				<connection-list>
					<connection id="4" x-location="0.0" y-location="4.5" />
				</connection-list>
			</building>

			<building id="6" type="MD1 Nuclear Reactor" x-location="40.0" y-location="-60.0" facing="0.0" />
			<building id="7" type="MD1 Nuclear Reactor" x-location="40.0" y-location="-80.0" facing="0.0" />
			<building id="8" type="MD1 Nuclear Reactor" x-location="60.0" y-location="-60.0" facing="0.0" />

			<building id="9" type="Starting ERV Base" x-location="40.0" y-location="15.0" facing="135.0" />

			<building id="10" type="ERV Base" x-location="40.0" y-location="-15.0" facing="45.0" />

			<building id="11" type="Large Sabatier Processor" x-location="0.0" y-location="-40.0" facing="90.0" />

			<building id="12" type="Large Sabatier Processor" x-location="0.0" y-location="-65.0" facing="90.0" />		

			<vehicle type="Explorer Rover" number="2" />
			<vehicle type="Light Utility Vehicle" number="1" />

			<equipment type="EVA Suit" number="8" />
			<equipment type="Gas Canister" number="40" />
			<equipment type="Barrel" number="40" />
			<equipment type="Bag" number="40" />
			<equipment type="Large Bag" number="10" />
			<equipment type="Specimen Box" number="50" />

			<part-package name="package 1" number="1" />

			<resupply>
				<resupply-mission name="Mars Direct Base Resupply 1" arrival-time="668.0" />
				<resupply-mission name="Mars Direct Base Resupply 2" arrival-time="1336.0" />
				<resupply-mission name="Mars Direct Base Resupply 3" arrival-time="2004.0" />
			</resupply>
		</template>
				
		<template name="Mars Direct Base (Phase 2)" default-population="8" number-of-robots="4" sponsor="Mars Society (MS)">
			<building id="0" type="Lander Hab" x-location="0.0" y-location="0.0" facing="0.0">
				<connection-list>
					<connection id="1" x-location="0.0" y-location="4.5" />
					<connection id="3" x-location="4.5" y-location="0.0" />
				</connection-list>
			</building>
			<building id="1" type="Hallway" length="4.0" x-location="0.0" y-location="6.5" facing="0.0">
				<connection-list>
					<connection id="0" x-location="0.0" y-location="-2.0" />
					<connection id="2" x-location="0.0" y-location="2.0" />
				</connection-list>
			</building>
			<building id="2" type="Lander Hab" x-location="0.0" y-location="13.0" facing="0.0">
				<connection-list>
					<connection id="1" x-location="0.0" y-location="-4.5" />
					<connection id="5" x-location="-4.5" y-location="0.0" />
					<connection id="3" x-location="4.5" y-location="0.0" />
				</connection-list>
			</building>
			<!-- EVA Airlock is attached to the lander hab -->
			<building id="3" type="EVA Airlock" x-location="7.5" y-location="0.0" facing="0.0">
				<connection-list>
					<connection id="2" x-location="-3.0" y-location="0.0" />
				</connection-list>
			</building>
			<building id="4" type="Hallway" length="3.0" x-location="-6.0" y-location="0.0" facing="270.0">
				<connection-list>
					<connection id="0" x-location="0.0" y-location="1.5" />
					<connection id="5" x-location="0.0" y-location="-1.5" />
				</connection-list>
			</building>
			<building id="5" type="Inflatable Greenhouse" x-location="-12.0" y-location="0.0" facing="270.0">
				<connection-list>
					<connection id="4" x-location="0.0" y-location="4.5" />
				</connection-list>
			</building>
			<building id="6" type="Hallway" length="3.0" x-location="-6.0" y-location="13.0" facing="270.0">
				<connection-list>
					<connection id="2" x-location="0.0" y-location="1.5" />
					<connection id="7" x-location="0.0" y-location="-1.5" />
				</connection-list>
			</building>
			<building id="7" type="Inflatable Greenhouse" x-location="-12.0" y-location="13.0" facing="270.0">
				<connection-list>
					<connection id="6" x-location="0.0" y-location="4.5" />
				</connection-list>
			</building>
					
			<building id="8" type="MD1 Nuclear Reactor" x-location="40.0" y-location="-60.0" facing="0.0" />
			<building id="9" type="MD1 Nuclear Reactor" x-location="40.0" y-location="-80.0" facing="0.0" />
			<building id="10" type="MD1 Nuclear Reactor" x-location="60.0" y-location="-60.0" facing="0.0" />
			<building id="11" type="MD1 Nuclear Reactor" x-location="60.0" y-location="-80.0" facing="0.0" />
								
			<building id="12" type="Starting ERV Base" x-location="40.0" y-location="45.0" facing="135.0" />
			<building id="13" type="ERV Base" x-location="40.0" y-location="15.0" facing="135.0" />
			<building id="14" type="ERV Base" x-location="40.0" y-location="-15.0" facing="45.0" />
	
			<building id="15" type="Large Sabatier Processor" x-location="0.0" y-location="-40.0" facing="90.0" />
			<building id="16" type="Large Sabatier Processor" x-location="0.0" y-location="-45.0" facing="90.0" />
					
			<vehicle type="Explorer Rover" number="2" />
			<vehicle type="Light Utility Vehicle" number="1" />
			
			<equipment type="EVA Suit" number="16" />
			<equipment type="Gas Canister" number="80" />
			<equipment type="Barrel" number="80" />
			<equipment type="Bag" number="80" />
			<equipment type="Large Bag" number="20" />
			<equipment type="Specimen Box" number="50" />


			<!-- Resources -->
			<resource type="food" amount="4000.0" />
			<resource type="water" amount="6000.0" />	
						
			<resource type="black water" amount="25.0" />			
			<resource type="grey water" amount="25.0" />			
			<resource type="food waste" amount="25.0" />			
			<resource type="solid waste" amount="25.0" />			
			<resource type="crop waste" amount="25.0" />	
	
<!--		
			<resource type="nitrogen" amount="1000.0" />			
			<resource type="hydrogen" amount="6000.0" />					
			<resource type="methane" amount="6000.0" />			
			<resource type="carbon dioxide" amount="10.0" />
-->

			<resource type="argon" amount="60.0" />		
			
			<resource type="fertilizer" amount="50.0" />

			<!-- Crop -->
			<resource type="Blueberry" amount="50.0" />
			<resource type="Cabbage" amount="50.0" />
			<resource type="Carrot" amount="50.0" />
			<resource type="Celery" amount="50.0" />
			<resource type="Corn" amount="50.0" />
			
			<resource type="Cranberry" amount="50.0" />
			<resource type="Cucumber" amount="50.0" />
			<resource type="Garlic" amount="50.0" />
			<resource type="Ginger" amount="50.0" />
			<resource type="Green Bell Pepper" amount="50.0" />
			
			<resource type="Spring Onion" amount="50.0" />
			<resource type="Kidney Bean" amount="50.0" />
			<resource type="Lettuce" amount="50.0" />
			<resource type="Peanut" amount="50.0" />
			<resource type="Peas" amount="50.0" />
			
			<resource type="Potato" amount="50.0" />
			<resource type="Quinoa" amount="50.0" />
			<resource type="Rice" amount="50.0" />		
			<resource type="Soybean" amount="50.0" />
			<resource type="Strawberry" amount="50.0" />
			
			<resource type="Sugarcane" amount="50.0" />		
			<resource type="Swiss Chard" amount="50.0" />
			<resource type="Taro" amount="50.0" />
			<resource type="Tomato" amount="50.0" />
			
			<resource type="Wheat" amount="50.0" />
			<resource type="White Rice" amount="50.0" />
			<resource type="White Onion" amount="50.0" />
			<resource type="Yam" amount="50.0" />

			<resource type="morel mushroom" amount="50.0" />